# -*- coding: utf-8 -*-
"""第五章补题批次1: choice 30 + truefalse 10"""
import json, io, sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
P = r'C:\Users\Lenovo\Desktop\湖南大学\细胞生物学题库\第五章\questions.json'
qs = json.load(open(P, encoding='utf-8'))

NEW = [
# ---- choice 30 (细胞质基质/热激蛋白/泛素-蛋白酶体/内质网/ERS) ----
{"type": "choice", "question": "下列代谢过程不在细胞质基质中进行的是（　）",
 "options": {"A": "糖酵解", "B": "磷酸戊糖途径", "C": "三羧酸循环", "D": "脂肪酸的合成"},
 "answer": "C",
 "explanation": "三羧酸循环在线粒体基质中进行；细胞质基质中进行糖酵解、磷酸戊糖途径、糖原合成与分解、脂肪酸合成等中间代谢过程。",
 "difficulty": 1, "tags": ["细胞质基质", "代谢功能"], "topic": "细胞质基质"},
{"type": "choice", "question": "细胞内所有蛋白质合成的起始步骤均发生在（　）",
 "options": {"A": "细胞质基质中的游离核糖体", "B": "糙面内质网附着核糖体", "C": "线粒体核糖体", "D": "核仁"},
 "answer": "A",
 "explanation": "细胞内所有蛋白质合成的起始步骤都发生在细胞质基质内的游离核糖体上；合成分泌蛋白、跨膜蛋白的核糖体随后转移至内质网继续合成。",
 "difficulty": 1, "tags": ["细胞质基质", "蛋白质合成"], "topic": "细胞质基质"},
{"type": "choice", "question": "下列不属于细胞质基质中蛋白质修饰方式的是（　）",
 "options": {"A": "磷酸化与去磷酸化", "B": "甲基化", "C": "酰基化", "D": "二硫键的形成"},
 "answer": "D",
 "explanation": "二硫键的形成主要发生在内质网中（内质网膜中多肽链半胱氨酸残基间形成）。细胞质基质中的蛋白修饰包括磷酸化/去磷酸化、甲基化、酰基化及部分糖基化等。",
 "difficulty": 2, "tags": ["细胞质基质", "蛋白质修饰"], "topic": "细胞质基质"},
{"type": "choice", "question": "细胞质基质中决定蛋白质寿命的信号存在于蛋白质的（　）",
 "options": {"A": "N端第一个氨基酸残基", "B": "C端最后一个氨基酸残基", "C": "中部疏水区", "D": "信号肽序列"},
 "answer": "A",
 "explanation": "决定蛋白质寿命的信号存在于蛋白质N端的第一个氨基酸残基：若为Met、Ser、Thr、Ala、Val、Cys、Gly或Pro则蛋白质往往稳定，否则往往不稳定。",
 "difficulty": 2, "tags": ["细胞质基质", "蛋白质寿命"], "topic": "细胞质基质"},
{"type": "choice", "question": "若蛋白质N端第一个氨基酸为下列哪种，该蛋白质往往是不稳定的（　）",
 "options": {"A": "Met", "B": "Ser", "C": "Ala", "D": "Phe"},
 "answer": "D",
 "explanation": "N端第一个氨基酸为Met、Ser、Thr、Ala、Val、Cys、Gly或Pro时蛋白质往往稳定；Phe不在稳定名单中，属不稳定氨基酸。",
 "difficulty": 2, "tags": ["细胞质基质", "蛋白质寿命"], "topic": "细胞质基质"},
{"type": "choice", "question": "Src基因产物的豆蔻酰化修饰的意义是（　）",
 "options": {"A": "帮助其结合细胞质膜", "B": "帮助其进入细胞核", "C": "促进其降解", "D": "增强其磷酸化活性"},
 "answer": "A",
 "explanation": "酰基化修饰中有一类如Src基因产物的豆蔻酰化，可帮助其结合细胞质膜；微管蛋白的乙酰化则与细胞结构组装功能相关。",
 "difficulty": 3, "tags": ["细胞质基质", "酰基化"], "topic": "细胞质基质"},
{"type": "choice", "question": "组蛋白的甲基化主要与下列哪项生理过程相关（　）",
 "options": {"A": "蛋白质降解", "B": "基因表达调控与表观遗传", "C": "细胞骨架组装", "D": "细胞凋亡执行"},
 "answer": "B",
 "explanation": "细胞骨架蛋白N端甲基化可防水解；组蛋白甲基化与基因表达调控、表观遗传相关。",
 "difficulty": 2, "tags": ["细胞质基质", "甲基化"], "topic": "细胞质基质"},
{"type": "choice", "question": "关于热激蛋白表达方式的描述，正确的是（　）",
 "options": {"A": "仅在胁迫条件下表达", "B": "大多数为组成型表达，部分成员在胁迫条件下高水平表达", "C": "仅在线粒体中表达", "D": "仅存在于原核生物"},
 "answer": "B",
 "explanation": "热激蛋白中大多数是组成型表达并执行多种基本功能，有些是细胞在胁迫条件下高水平表达，以在维持细胞稳态中发挥核心作用。",
 "difficulty": 1, "tags": ["细胞质基质", "热激蛋白"], "topic": "细胞质基质"},
{"type": "choice", "question": "大肠杆菌中Hsp60家族分子伴侣的代表是（　）",
 "options": {"A": "GroEL", "B": "Sec61", "C": "蛋白二硫键异构酶", "D": "钙联蛋白"},
 "answer": "A",
 "explanation": "Hsp60家族的代表如大肠杆菌的GroEL，与GroES协同形成笼状结构，协助蛋白质折叠为活性构象；线粒体、叶绿体中也有Hsp60同源物。",
 "difficulty": 2, "tags": ["细胞质基质", "分子伴侣", "Hsp60"], "topic": "细胞质基质"},
{"type": "choice", "question": "泛素结合酶E2又称（　）",
 "options": {"A": "泛素活化酶", "B": "泛素载体蛋白", "C": "泛素连接酶", "D": "泛素特异性蛋白酶"},
 "answer": "B",
 "explanation": "泛素化的三种酶：泛素活化酶（E1）、泛素结合酶（E2，又称泛素载体蛋白）和泛素连接酶（E3）。",
 "difficulty": 1, "tags": ["蛋白质降解", "泛素化酶"], "topic": "泛素化"},
{"type": "choice", "question": "蛋白酶体的分子质量约为（　）",
 "options": {"A": "500~800 kDa", "B": "2000~2400 kDa", "C": "4000~6000 kDa", "D": "10000 kDa以上"},
 "answer": "B",
 "explanation": "蛋白酶体是细胞内降解蛋白质的大分子复合体，由约50种亚基组成，分子质量2000~2400 kDa，具有蛋白酶活性。",
 "difficulty": 2, "tags": ["蛋白质降解", "蛋白酶体"], "topic": "泛素化"},
{"type": "choice", "question": "26S蛋白酶体的20S催化核心由约多少种亚基组成（　）",
 "options": {"A": "19种", "B": "28种", "C": "50种", "D": "76种"},
 "answer": "B",
 "explanation": "20S催化核心由28种亚基组成桶状结构；19S调节亚基由19种亚基组成，一个或两个19S调节亚基像“帽子”一样结合在20S两端。",
 "difficulty": 2, "tags": ["蛋白质降解", "蛋白酶体"], "topic": "泛素化"},
{"type": "choice", "question": "19S调节亚基中与20S催化核心接触的6种亚基具有（　）",
 "options": {"A": "蛋白酶活性", "B": "ATP酶活性", "C": "GTP酶活性", "D": "磷酸酶活性"},
 "answer": "B",
 "explanation": "19S调节亚基负责识别泛素化底物蛋白、切除泛素修饰及使蛋白去折叠，其中与20S催化核心接触的6种亚基具有ATP酶活性。",
 "difficulty": 3, "tags": ["蛋白质降解", "蛋白酶体"], "topic": "泛素化"},
{"type": "choice", "question": "泛素-蛋白酶体途径的生物学意义不包括（　）",
 "options": {"A": "清除错误折叠和需存量调控的蛋白质", "B": "参与细胞周期调控", "C": "参与DNA修复与免疫功能调控", "D": "直接合成ATP供能"},
 "answer": "D",
 "explanation": "泛素控制的蛋白质降解能清除错误折叠及需要存量调控的蛋白质，对细胞周期调控、DNA修复、细胞生长、免疫功能等有重要调控作用；但该途径不直接合成ATP。",
 "difficulty": 2, "tags": ["蛋白质降解", "泛素化"], "topic": "泛素化"},
{"type": "choice", "question": "蛋白酶体被形象地称为（　）",
 "options": {"A": "蛋白质合成机器", "B": "细胞内蛋白质破碎机", "C": "细胞内的分子伴侣", "D": "溶酶体的前体结构"},
 "answer": "B",
 "explanation": "蛋白酶体具有蛋白酶活性，其功能被誉为“细胞内蛋白质破碎机”，如26S蛋白酶体。",
 "difficulty": 1, "tags": ["蛋白质降解", "蛋白酶体"], "topic": "泛素化"},
{"type": "choice", "question": "内质网是真核细胞中（　）",
 "options": {"A": "最大的膜性细胞器", "B": "最小的细胞器", "C": "唯一的单层膜细胞器", "D": "双层膜细胞器"},
 "answer": "A",
 "explanation": "内质网是真核细胞中最大的膜性细胞器，包括核膜和延伸到细胞质内的外周内质网，约占细胞膜系统的一半。",
 "difficulty": 1, "tags": ["内质网", "结构"], "topic": "内质网"},
{"type": "choice", "question": "片层状内质网一般位于（　）",
 "options": {"A": "细胞周缘", "B": "核膜周围", "C": "细胞膜下方", "D": "高尔基体旁"},
 "answer": "B",
 "explanation": "片层状内质网一般位于核膜周围，大部分是有核糖体附着的内质网，属于糙面内质网，是膜蛋白和分泌蛋白的合成加工场所。",
 "difficulty": 1, "tags": ["内质网", "rER", "结构"], "topic": "内质网"},
{"type": "choice", "question": "下列细胞中糙面内质网（rER）非常发达的是（　）",
 "options": {"A": "成熟红细胞", "B": "胰腺腺泡细胞", "C": "成熟精子", "D": "骨骼肌细胞"},
 "answer": "B",
 "explanation": "分泌活动旺盛的细胞（如胰腺腺泡细胞、分泌抗体的浆细胞）中rER非常发达；未分化的细胞与肿瘤细胞中rER较为稀少。",
 "difficulty": 1, "tags": ["内质网", "rER"], "topic": "内质网"},
{"type": "choice", "question": "在肝细胞中非常发达并具备解毒等特殊功能的内质网是（　）",
 "options": {"A": "糙面内质网", "B": "光面内质网", "C": "核膜", "D": "肌质网"},
 "answer": "B",
 "explanation": "肝细胞的光面内质网非常发达，可合成外输性脂蛋白并通过细胞色素P450家族酶系解毒；合成固醇类激素的细胞中sER同样非常发达。",
 "difficulty": 1, "tags": ["内质网", "sER"], "topic": "内质网"},
{"type": "choice", "question": "光面内质网常作为何种结构的出芽位点（　）",
 "options": {"A": "核糖体", "B": "转运膜泡", "C": "溶酶体", "D": "过氧化物酶体"},
 "answer": "B",
 "explanation": "sER所占区域通常较小，常作为出芽的位点，转运内质网合成的蛋白质或脂类到高尔基体。",
 "difficulty": 2, "tags": ["内质网", "sER"], "topic": "内质网"},
{"type": "choice", "question": "合成代谢旺盛的细胞中，糙面内质网常与哪种细胞器相邻（　）",
 "options": {"A": "溶酶体", "B": "线粒体", "C": "过氧化物酶体", "D": "中心体"},
 "answer": "B",
 "explanation": "合成代谢旺盛的细胞中，rER总与线粒体相邻，此分布与功能所需能量、脂类转移、Ca2+释放调节相关。",
 "difficulty": 2, "tags": ["内质网", "细胞器关系"], "topic": "内质网"},
{"type": "choice", "question": "细胞分裂时内质网的变化是（　）",
 "options": {"A": "保持原有结构不变", "B": "经历解体与重建", "C": "与细胞膜完全融合", "D": "转化为高尔基体"},
 "answer": "B",
 "explanation": "细胞分裂时，内质网会经历解体与重建的过程；同一细胞在不同发育阶段、不同生理状态下，内质网的结构与功能也会显著变化。",
 "difficulty": 1, "tags": ["内质网", "动态变化"], "topic": "内质网"},
{"type": "choice", "question": "哺乳动物细胞UPR中，IRE1通路切割的前体mRNA是（　）",
 "options": {"A": "XBP1", "B": "PERK", "C": "ATF6", "D": "eIF2α"},
 "answer": "A",
 "explanation": "IRE1激活RNA内切酶活性后切割特定前体mRNA（酵母为Hac1，哺乳动物为XBP1），产生有功能的mRNA，翻译出的转录因子进入细胞核激活UPR相关基因转录。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "choice", "question": "内质网应激时，IRE1还通过切割哪种RNA抑制蛋白质翻译（　）",
 "options": {"A": "5S rRNA", "B": "28S rRNA", "C": "tRNA", "D": "mRNA的5′帽结构"},
 "answer": "B",
 "explanation": "IRE1除切割XBP1/Hac1前体mRNA外，还能切割28S rRNA，抑制蛋白质翻译，从而减轻内质网负荷。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "choice", "question": "PERK通路通过磷酸化哪种因子全局性减缓蛋白质合成（　）",
 "options": {"A": "eIF4E", "B": "eIF2α", "C": "核糖体蛋白S6", "D": "组蛋白H3"},
 "answer": "B",
 "explanation": "PERK二聚化并交叉磷酸化激活后，磷酸化翻译起始因子eIF2α，全局性减缓或暂停蛋白质合成，减轻内质网负荷。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "choice", "question": "内质网应激时，PERK抑制细胞周期蛋白D1的翻译，导致细胞周期（　）",
 "options": {"A": "G1期停顿", "B": "S期加速", "C": "M期阻滞", "D": "不受影响"},
 "answer": "A",
 "explanation": "PERK能特异性抑制细胞周期蛋白D1翻译，导致细胞周期G1期停顿，减缓细胞增殖以应对内质网应激。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "choice", "question": "内质网应激时，ATF6的激活方式是（　）",
 "options": {"A": "在胞质中被直接磷酸化", "B": "被转运至高尔基体并被S1P和S2P蛋白酶剪切", "C": "直接入核与DNA结合", "D": "被泛素化降解"},
 "answer": "B",
 "explanation": "ERS时，位于内质网膜的ATF6被转运至高尔基体，被S1P和S2P蛋白酶剪切激活，激活后的ATF6进入细胞核，促进含ERSE元件的UPR靶基因转录。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "choice", "question": "内质网腔中高浓度Ca2+对膜泡形成的作用是（　）",
 "options": {"A": "促进内质网出芽形成转运膜泡", "B": "阻止内质网出芽形成转运膜泡", "C": "无任何影响", "D": "促进膜泡与靶膜融合"},
 "answer": "B",
 "explanation": "内质网含4种以上Ca2+结合蛋白（如BiP）且浓度较高，每个蛋白可结合约30个Ca2+；高浓度Ca2+可阻止内质网出芽形成转运膜泡，Ca2+浓度变化调节膜泡形成。",
 "difficulty": 3, "tags": ["内质网", "Ca2+调节"], "topic": "内质网"},
{"type": "choice", "question": "用衣霉素阻断蛋白质糖基化，会导致（　）",
 "options": {"A": "蛋白质合成完全停止", "B": "分泌的抗体IgG或质膜糖蛋白不能正确折叠", "C": "蛋白质降解速度加快", "D": "内质网结构消失"},
 "answer": "B",
 "explanation": "缺少糖基侧链的蛋白质不能正确折叠，需留在内质网中。例如用衣霉素阻断糖基化会导致分泌的抗体IgG或分泌到质膜上的糖蛋白如血凝素不能正确折叠。",
 "difficulty": 3, "tags": ["内质网", "糖基化", "质量监控"], "topic": "内质网"},
{"type": "choice", "question": "肺囊性纤维病的发病机理是（　）",
 "options": {"A": "溶酶体水解酶缺失", "B": "离子通道蛋白突变致功能异常", "C": "过氧化物酶体功能丧失", "D": "蛋白酶体降解功能缺陷"},
 "answer": "B",
 "explanation": "肺囊性纤维病属错误折叠导致的功能丢失型疾病，其发病机理是离子通道蛋白（CFTR）突变（蛋白错误折叠）致功能异常。",
 "difficulty": 2, "tags": ["内质网", "错误折叠", "疾病"], "topic": "内质网"},
{"type": "choice", "question": "亨廷顿舞蹈症的发病与下列哪种结构有关（　）",
 "options": {"A": "淀粉样蛋白斑块", "B": "亨廷顿蛋白形成的毒性聚合体", "C": "溶酶体内膜糖蛋白堆积", "D": "过氧化物酶体晶格结构"},
 "answer": "B",
 "explanation": "亨廷顿舞蹈症属错误折叠蛋白形成毒性聚合体的功能获得型疾病，其发病机理是亨廷顿蛋白聚合体的形成；阿尔茨海默病的Aβ淀粉样斑块则与之不同。",
 "difficulty": 2, "tags": ["内质网", "错误折叠", "疾病"], "topic": "内质网"},
# ---- truefalse 10 ----
{"type": "truefalse", "question": "细胞质基质中不存在任何形式的蛋白质糖基化修饰。",
 "answer": "false",
 "explanation": "哺乳动物细胞的细胞质基质中也可发生糖基化，主要是将N-乙酰葡萄糖胺加到蛋白质丝氨酸的羟基上；但糖基化修饰主要发生在内质网和高尔基体中。",
 "difficulty": 2, "tags": ["细胞质基质", "蛋白质修饰"], "topic": "细胞质基质"},
{"type": "truefalse", "question": "细胞内所有蛋白质合成的起始步骤都发生在细胞质基质内的游离核糖体上。",
 "answer": "true",
 "explanation": "细胞内所有蛋白质合成的起始步骤均发生在细胞质基质游离核糖体上，部分蛋白质起始合成后转移至内质网膜继续完成肽链延伸。",
 "difficulty": 1, "tags": ["细胞质基质", "蛋白质合成"], "topic": "细胞质基质"},
{"type": "truefalse", "question": "泛素活化过程不需要ATP参与。",
 "answer": "false",
 "explanation": "泛素分子通过泛素活化酶（E1）激活形成酰基-腺苷酸中介物，该反应需要ATP的参与。",
 "difficulty": 1, "tags": ["蛋白质降解", "泛素化"], "topic": "泛素化"},
{"type": "truefalse", "question": "蛋白酶体降解靶蛋白前需要将靶蛋白去折叠。",
 "answer": "true",
 "explanation": "蛋白酶体19S调节亚基识别泛素化靶蛋白并使其去折叠，然后转移至20S催化核心内降解。",
 "difficulty": 2, "tags": ["蛋白质降解", "蛋白酶体"], "topic": "泛素化"},
{"type": "truefalse", "question": "内质网是真核细胞中最普遍、形态多变、适应性最强的细胞器之一。",
 "answer": "true",
 "explanation": "内质网是真核细胞中普遍存在、形态多变、适应性最强的细胞器之一，由封闭的管状或扁平囊状膜系统及其包被的腔形成三维网络。",
 "difficulty": 1, "tags": ["内质网", "结构"], "topic": "内质网"},
{"type": "truefalse", "question": "管状内质网表面通常附着大量核糖体。",
 "answer": "false",
 "explanation": "管状内质网一般没有核糖体附着，属于光面内质网，主要发挥脂质合成、信号转导、与其他细胞器相互作用等功能。",
 "difficulty": 1, "tags": ["内质网", "sER"], "topic": "内质网"},
{"type": "truefalse", "question": "内质网应激时，IRE1通路切割28S rRNA以抑制蛋白质翻译。",
 "answer": "true",
 "explanation": "IRE1激活后除切割XBP1/Hac1前体mRNA产生有功能的转录因子外，还能切割28S rRNA，抑制蛋白质翻译，减轻内质网负荷。",
 "difficulty": 3, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "truefalse", "question": "正常情况下，ATF6与伴侣蛋白BiP/GRP78结合而处于失活状态。",
 "answer": "true",
 "explanation": "哺乳动物细胞通过三种内质网膜蛋白感应ERS信号，正常情况下它们与BiP/GRP78结合而失活；错误折叠蛋白积累时BiP被竞争性结合而解离，从而激活三条平行信号途径。",
 "difficulty": 2, "tags": ["内质网应激", "UPR"], "topic": "内质网"},
{"type": "truefalse", "question": "高尔基体是高度动态的结构，在不同细胞或同一细胞生长的不同阶段形态差异很大。",
 "answer": "true",
 "explanation": "高尔基体属于高度动态的结构，在不同细胞中或同一细胞生长的不同阶段，其形态结构会有很大变化。",
 "difficulty": 1, "tags": ["高尔基体", "结构"], "topic": "高尔基体"},
{"type": "truefalse", "question": "TGN内的pH低于高尔基体的其他部位。",
 "answer": "true",
 "explanation": "TGN呈管网状，外侧伸入反面侧细胞质中，其内pH可能低于高尔基体的其他部位。",
 "difficulty": 2, "tags": ["高尔基体", "TGN"], "topic": "高尔基体"},
]

for q in NEW:
    q['id'] = len(qs) + 1
    qs.append(q)

json.dump(qs, open(P, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('第五章批次1落盘，当前总数:', len(qs))
