# -*- coding: utf-8 -*-
"""第六章补题批次2: choice 17 + truefalse 9 (膜泡运输/COPII/COPI/网格蛋白/锚定融合)"""
import json, io, sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
P = r'C:\Users\Lenovo\Desktop\湖南大学\细胞生物学题库\第六章\questions.json'
qs = json.load(open(P, encoding='utf-8'))

NEW = [
# ---- choice 17 ----
{"type": "choice", "question": "膜泡运输中，转运膜泡在细胞内的移动依赖（　）",
 "options": {"A": "分子马达沿微管或微丝驱动", "B": "自由扩散", "C": "核孔复合体转运", "D": "胞质环流"},
 "answer": "A",
 "explanation": "膜泡在分子马达介导下沿微管或微丝转运至目的地，与靶细胞器或细胞膜融合，这是膜泡运输的关键步骤之一。",
 "difficulty": 1, "tags": ["膜泡运输", "细胞骨架"], "topic": "膜泡运输"},
{"type": "choice", "question": "转运膜泡可以携带的“货物”包括（　）",
 "options": {"A": "可溶性蛋白、膜蛋白与膜脂", "B": "仅可溶性蛋白", "C": "仅膜蛋白", "D": "仅小分子离子"},
 "answer": "A",
 "explanation": "膜泡运输不仅涉及蛋白质的转运，还介导膜脂等组分的转运，可溶性蛋白、膜蛋白与膜脂均可作为货物被包装进转运膜泡。",
 "difficulty": 2, "tags": ["膜泡运输", "货物"], "topic": "膜泡运输"},
{"type": "choice", "question": "COPI包被膜泡的分离与鉴定方法是（　）",
 "options": {"A": "用不能被水解的GTP类似物处理细胞诱导聚集，再经密度梯度离心分离", "B": "荧光显微镜直接观察", "C": "免疫共沉淀", "D": "PCR扩增"},
 "answer": "A",
 "explanation": "COPI包被膜泡可通过用不能被水解的GTP类似物处理细胞诱导其聚集，并通过密度梯度离心法从细胞匀浆中分离。",
 "difficulty": 3, "tags": ["COPI", "研究方法"], "topic": "膜泡运输"},
{"type": "choice", "question": "驻留蛋白被错误包装进入转运膜泡后成为（　）",
 "options": {"A": "逃逸蛋白", "B": "信号肽", "C": "转运蛋白", "D": "分子伴侣"},
 "answer": "A",
 "explanation": "驻留蛋白因某些原因未被正确分选、被错误包装进入转运膜泡，从而逃逸到其本不应存在的细胞器中，就形成了逃逸蛋白。",
 "difficulty": 1, "tags": ["逃逸蛋白", "COPI"], "topic": "膜泡运输"},
{"type": "choice", "question": "COPII膜泡运输的选择特异性依赖（　）",
 "options": {"A": "被转运蛋白的靶向分选序列，膜泡包被直接识别并结合", "B": "蛋白质的分子量大小", "C": "膜泡运输速率", "D": "细胞质基质中的离子浓度"},
 "answer": "A",
 "explanation": "COPII膜泡运输具有选择特异性，依赖被转运蛋白的靶向分选序列，以此区分需包装转运的蛋白与需排除的滞留蛋白，膜泡包被直接识别并结合靶向序列或分选信号。",
 "difficulty": 2, "tags": ["COPII", "选择特异性"], "topic": "膜泡运输"},
{"type": "choice", "question": "COPI包被膜泡逆向运输的路径是（　）",
 "options": {"A": "内质网→高尔基体", "B": "高尔基体反面膜囊→顺面膜囊/CGN→内质网", "C": "高尔基体→细胞膜", "D": "细胞膜→内体"},
 "answer": "B",
 "explanation": "COPI介导逆向运输，具体路径为：高尔基体反面膜囊→高尔基体顺面膜囊、顺面网状区（CGN）→内质网。",
 "difficulty": 1, "tags": ["COPI", "逆向运输"], "topic": "膜泡运输"},
{"type": "choice", "question": "COPI包被膜泡运输的生物学意义是（　）",
 "options": {"A": "防止内质网腔蛋白损失，维持细胞器蛋白质组分特异性", "B": "降解错误折叠蛋白", "C": "促进细胞分裂", "D": "合成新的膜脂"},
 "answer": "A",
 "explanation": "COPI运输防止内质网腔蛋白（如参与新合成分泌蛋白正确折叠的分子伴侣）的损失；每种膜组分具有自身独特的回收信号，使细胞器在膜泡不断运动过程中保持独特蛋白质组分。",
 "difficulty": 2, "tags": ["COPI", "意义"], "topic": "膜泡运输"},
{"type": "choice", "question": "分泌途径中，网格蛋白/接头蛋白包被膜泡从TGN转运货物至（　）",
 "options": {"A": "细胞膜、内体、溶酶体、黑色素体、血小板囊泡和植物细胞液泡", "B": "仅细胞膜", "C": "内质网", "D": "线粒体和叶绿体"},
 "answer": "A",
 "explanation": "在分泌途径中，网格蛋白/接头蛋白包被膜泡负责从高尔基体TGN向细胞膜、内体、溶酶体、黑色素体、血小板囊泡和植物细胞液泡的货物转运过程中膜泡的形成。",
 "difficulty": 2, "tags": ["网格蛋白", "分泌途径"], "topic": "膜泡运输"},
{"type": "choice", "question": "GGA接头蛋白的结构特点是（　）",
 "options": {"A": "由单一多肽链组成", "B": "异四聚体", "C": "同四聚体", "D": "三腿结构"},
 "answer": "A",
 "explanation": "经典接头蛋白复合物为AP1、AP2、AP3三种（均为异四聚体）；其他接头蛋白如GGA由单一多肽链组成。",
 "difficulty": 3, "tags": ["接头蛋白", "GGA"], "topic": "膜泡运输"},
{"type": "choice", "question": "关于AP3复合物包被蛋白的正确说法是（　）",
 "options": {"A": "是否含有网格蛋白未知", "B": "肯定不含网格蛋白", "C": "由三腿结构组成", "D": "仅存在于植物细胞"},
 "answer": "A",
 "explanation": "AP1、AP2、AP3三种经典接头蛋白复合物中，AP3复合物的包被蛋白是否含有网格蛋白目前未知。",
 "difficulty": 3, "tags": ["接头蛋白", "AP3"], "topic": "膜泡运输"},
{"type": "choice", "question": "新近证据表明，胞吞过程中网格蛋白包被膜泡的形成（　）",
 "options": {"A": "不需要ARF参与", "B": "完全依赖ARF", "C": "依赖Sar1", "D": "依赖Rab蛋白"},
 "answer": "A",
 "explanation": "网格蛋白包被膜泡大部分需要ARF参与，但新近证据表明在胞吞作用过程中不需要ARF参与。",
 "difficulty": 3, "tags": ["ARF", "网格蛋白", "内吞"], "topic": "膜泡运输"},
{"type": "choice", "question": "网格蛋白在供体膜上聚合后，其后续作用是（　）",
 "options": {"A": "募集接头蛋白复合物到供体膜的胞质面并与之结合", "B": "直接水解GTP使膜泡断裂", "C": "识别KDEL信号", "D": "关闭移位子"},
 "answer": "A",
 "explanation": "网格蛋白在供体膜上聚合后，可募集接头蛋白复合物到供体膜的胞质面并与之结合，共同组装形成包被并驱动膜出芽；膜泡断裂由发动蛋白完成。",
 "difficulty": 2, "tags": ["网格蛋白", "装配"], "topic": "膜泡运输"},
{"type": "choice", "question": "下列不属于膜泡运输三个关键步骤的是（　）",
 "options": {"A": "供体膜出芽、装配和断裂形成包被转运膜泡", "B": "马达蛋白驱动膜泡沿微管运输", "C": "转运膜泡与靶膜的锚定和融合", "D": "蛋白质的磷酸化修饰"},
 "answer": "D",
 "explanation": "膜泡运输的关键步骤包括供体膜的出芽、装配和断裂，马达蛋白驱动的膜泡运输，以及转运膜泡与靶膜的锚定和融合；蛋白质磷酸化修饰不属于膜泡运输的基本步骤。",
 "difficulty": 2, "tags": ["膜泡运输", "关键步骤"], "topic": "膜泡运输"},
{"type": "choice", "question": "Rab效应器的作用是（　）",
 "options": {"A": "与Rab-GTP结合使转运膜泡锚定在适当的靶膜上", "B": "水解GTP使膜泡断裂", "C": "合成类异戊二烯基团", "D": "切割信号肽"},
 "answer": "A",
 "explanation": "Rab-GTP通过类异戊二烯基团插入膜泡膜后，与靶膜上的Rab效应器结合，从而使转运膜泡被锚定在适当的靶膜上。",
 "difficulty": 2, "tags": ["Rab蛋白", "锚定"], "topic": "膜泡运输"},
{"type": "choice", "question": "膜泡运输中膜泡移动的“轨道”是（　）",
 "options": {"A": "微管（由马达蛋白驱动）", "B": "细胞质基质中的游离水分子", "C": "核孔复合体", "D": "内质网腔"},
 "answer": "A",
 "explanation": "膜泡在细胞内由马达蛋白驱动，以微管为轨道进行运输（在第八章细胞骨架部分详述）。",
 "difficulty": 1, "tags": ["膜泡运输", "微管"], "topic": "膜泡运输"},
{"type": "choice", "question": "COPII装配中，Sar1-GTP暴露出疏水N端插入ER膜后所起的作用是（　）",
 "options": {"A": "对包被蛋白的进一步装配起募集者作用", "B": "直接形成网格骨架", "C": "水解GTP为装配供能", "D": "识别货物分选信号"},
 "answer": "A",
 "explanation": "GTP结合引发Sar1构象改变，暴露出疏水N端并插入ER膜，膜结合的Sar1对包被蛋白的进一步装配起募集者作用，随后提供Sec23/Sec24复合物的结合位点。",
 "difficulty": 3, "tags": ["COPII", "Sar1"], "topic": "膜泡运输"},
{"type": "choice", "question": "内质网待转运膜蛋白的二酸分选信号（Asp-X-Glu）体现了COPII膜泡运输的（　）",
 "options": {"A": "选择特异性", "B": "能量来源", "C": "膜泡断裂机制", "D": "脱包被机制"},
 "answer": "A",
 "explanation": "内质网待转运膜蛋白具有二酸分选信号（如Asp-X-Glu），COPII中的Sec24亚基作为该信号的受体，识别结合后将膜蛋白包装进COPII膜泡，这体现了COPII膜泡运输的选择特异性。",
 "difficulty": 2, "tags": ["COPII", "选择特异性", "二酸信号"], "topic": "膜泡运输"},
# ---- truefalse 9 ----
{"type": "truefalse", "question": "叶绿体基质蛋白的输入主要依赖跨内膜的电化学梯度提供动力。",
 "answer": "false",
 "explanation": "与线粒体不同，叶绿体不产生跨内膜的电化学梯度，ATP水解供能几乎是叶绿体蛋白质转运唯一的动力来源。",
 "difficulty": 2, "tags": ["叶绿体", "翻译后转运"], "topic": "翻译后转运"},
{"type": "truefalse", "question": "类囊体蛋白分选的pH依赖途径需要跨内膜的pH梯度。",
 "answer": "true",
 "explanation": "pH依赖途径中，类囊体靶向序列N端精氨酸残基和跨内膜pH梯度是蛋白质进入类囊体腔的关键。",
 "difficulty": 3, "tags": ["叶绿体", "类囊体蛋白"], "topic": "翻译后转运"},
{"type": "truefalse", "question": "COPI包被膜泡在高尔基体膜囊之间发挥修饰酶类的回收利用作用。",
 "answer": "true",
 "explanation": "COPI包被膜泡介导从高尔基体回收货物转运至内质网的膜泡形成，也在高尔基体膜囊之间相关修饰酶类的回收利用中发挥作用。",
 "difficulty": 2, "tags": ["COPI", "回收"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "驻留蛋白形成的大复合物可被COPII膜泡顺利包装转运。",
 "answer": "false",
 "explanation": "转运膜泡将驻留蛋白有效排斥在外，如驻留蛋白形成大复合物后其尺寸过大无法被COPII膜泡包装，这是驻留蛋白维持定位的机制之一。",
 "difficulty": 2, "tags": ["驻留蛋白", "COPII"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "表达不能结合并水解GTP的突变型发动蛋白，会产生被发动蛋白包绕的、具有较长颈部的膜泡芽体。",
 "answer": "true",
 "explanation": "实验证据表明，若表达不能结合并水解GTP的突变型发动蛋白，则无法形成独立的膜泡，仅产生被发动蛋白包绕的、具有较长颈部的膜泡芽体。",
 "difficulty": 3, "tags": ["发动蛋白", "实验证据"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "GGA是由单一多肽链组成的接头蛋白。",
 "answer": "true",
 "explanation": "经典接头蛋白复合物AP1、AP2、AP3均为异四聚体，而其他接头蛋白如GGA由单一多肽链组成。",
 "difficulty": 2, "tags": ["接头蛋白", "GGA"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "膜泡融合发生后，Rab蛋白结合的GTP水解为GDP，Rab-GDP从膜泡释放。",
 "answer": "true",
 "explanation": "膜泡融合发生后，与Rab蛋白结合的GTP水解为GDP，引发Rab-GDP从膜泡释放，完成Rab的循环。",
 "difficulty": 2, "tags": ["Rab蛋白", "循环"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "SNARE复合体解离释放的蛋白亚基可循环用于其他融合事件。",
 "answer": "true",
 "explanation": "融合完成后，消耗ATP水解提供的能量使SNARE复合体解离，释放的SNARE蛋白亚基可再用于其他融合事件。",
 "difficulty": 2, "tags": ["SNARE", "膜融合"], "topic": "膜泡运输"},
{"type": "truefalse", "question": "新近证据表明，胞吞过程中网格蛋白包被膜泡的形成不需要ARF参与。",
 "answer": "true",
 "explanation": "网格蛋白包被膜泡大部分需要ARF参与，但新近证据表明在胞吞作用过程中不需要ARF参与。",
 "difficulty": 3, "tags": ["ARF", "内吞"], "topic": "膜泡运输"},
]

for q in NEW:
    q['id'] = len(qs) + 1
    qs.append(q)

json.dump(qs, open(P, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('第六章批次2落盘，当前总数:', len(qs))
