# -*- coding: utf-8 -*-
"""第六章补题批次1: choice 25 + truefalse 9 (分选总论/共翻译转运/跨膜蛋白/翻译后转运)"""
import json, io, sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
P = r'C:\Users\Lenovo\Desktop\湖南大学\细胞生物学题库\第六章\questions.json'
qs = json.load(open(P, encoding='utf-8'))

NEW = [
# ---- choice 25 ----
{"type": "choice", "question": "细胞质基质中的可溶性驻留蛋白和骨架蛋白的合成场所及转运方式是（　）",
 "options": {"A": "糙面内质网附着核糖体合成，共翻译转运", "B": "细胞质基质游离核糖体合成，翻译后转运", "C": "线粒体核糖体合成", "D": "高尔基体合成"},
 "answer": "B",
 "explanation": "细胞质基质中的可溶性驻留蛋白和骨架蛋白在细胞质基质游离核糖体上完成合成后留在细胞质基质中，属翻译后转运途径的范畴。",
 "difficulty": 2, "tags": ["翻译后转运", "蛋白质分选"], "topic": "翻译后转运"},
{"type": "choice", "question": "分泌蛋白从内质网转运至高尔基体所采用的转运方式是（　）",
 "options": {"A": "选择性门控转运", "B": "膜泡运输", "C": "跨膜转运", "D": "直接扩散"},
 "answer": "B",
 "explanation": "共翻译转运途径中，蛋白质进入内质网后经膜泡运输（COPII包被膜泡）从内质网转运至高尔基体，再分选至靶部位。",
 "difficulty": 1, "tags": ["膜泡运输", "蛋白质分选"], "topic": "膜泡运输"},
{"type": "choice", "question": "下列采用翻译后转运途径进入细胞器的蛋白质是（　）",
 "options": {"A": "分泌蛋白", "B": "细胞膜蛋白", "C": "过氧化物酶体基质蛋白", "D": "溶酶体酶"},
 "answer": "C",
 "explanation": "过氧化物酶体基质蛋白在细胞质基质游离核糖体上合成后，经翻译后转运途径进入过氧化物酶体；分泌蛋白、细胞膜蛋白和溶酶体酶均经共翻译转运途径。",
 "difficulty": 1, "tags": ["翻译后转运", "过氧化物酶体"], "topic": "翻译后转运"},
{"type": "choice", "question": "共翻译转运中信号肽被切除后的去向是（　）",
 "options": {"A": "随蛋白质进入内质网腔", "B": "被快速降解", "C": "返回细胞质基质重复使用", "D": "插入内质网膜形成跨膜区"},
 "answer": "B",
 "explanation": "内质网腔面的信号肽酶切除信号肽后将其快速降解，信号肽不会进入内质网腔。",
 "difficulty": 1, "tags": ["信号肽", "共翻译转运"], "topic": "共翻译转运"},
{"type": "choice", "question": "SRP中负责识别并结合信号肽的亚基是（　）",
 "options": {"A": "p54亚基", "B": "7S RNA", "C": "p19亚基", "D": "p72亚基"},
 "answer": "A",
 "explanation": "SRP由6种蛋白质和1个7S RNA组成，其中p54亚基负责识别并结合新生肽N端的信号肽，2分子GTP分别结合SRP-p54亚基和SRP受体α亚基以强化相互作用。",
 "difficulty": 3, "tags": ["SRP", "共翻译转运"], "topic": "共翻译转运"},
{"type": "choice", "question": "共翻译转运中肽链延伸暂时停止的生理意义是（　）",
 "options": {"A": "防止新生肽N端损伤和成熟前折叠", "B": "等待mRNA降解", "C": "为核糖体更换密码子", "D": "防止信号肽被切除"},
 "answer": "A",
 "explanation": "当多肽链延伸至约80个氨基酸残基时，N端内质网信号序列暴露并与SRP结合，导致肽链延伸暂时停止，防止新生肽N端损伤和成熟前折叠。",
 "difficulty": 2, "tags": ["SRP", "共翻译转运"], "topic": "共翻译转运"},
{"type": "choice", "question": "信号假说提出的实验背景是（　）",
 "options": {"A": "Palade发现游离核糖体合成非分泌蛋白、附着核糖体合成分泌蛋白", "B": "Watson发现DNA双螺旋", "C": "Blobel发现核糖体的化学组成", "D": "电镜观察发现高尔基体"},
 "answer": "A",
 "explanation": "Palade发现细胞质游离核糖体合成非分泌蛋白、内质网附着核糖体合成分泌蛋白，但无法解释两类核糖体的功能差异；Blobel和Sabatini据此提出信号假说，推测差异源于蛋白质本身。",
 "difficulty": 2, "tags": ["信号假说", "共翻译转运"], "topic": "共翻译转运"},
{"type": "choice", "question": "共翻译转运中，核糖体-新生肽复合物所结合的移位子的本质是（　）",
 "options": {"A": "内质网膜上的蛋白转运通道", "B": "细胞质基质中的游离蛋白", "C": "高尔基体上的受体", "D": "核糖体蛋白"},
 "answer": "A",
 "explanation": "移位子是内质网膜上的蛋白转运通道（如Sec61复合体），核糖体-新生肽复合物与其结合后，SRP解离，肽链继续合成并进入内质网腔。",
 "difficulty": 2, "tags": ["移位子", "共翻译转运"], "topic": "共翻译转运"},
{"type": "choice", "question": "信号肽在共翻译转运中的后期作用是（　）",
 "options": {"A": "与SRP结合暂停翻译", "B": "引导核糖体锚定内质网膜", "C": "打开移位子孔道", "D": "切除自身"},
 "answer": "C",
 "explanation": "呈环化构象的信号肽与移位子组分结合并打开孔道，信号肽穿入内质网膜，引导肽链以袢环形式进入内质网膜；除早期引导锚定外，打开移位子孔道是信号肽的后期作用。",
 "difficulty": 3, "tags": ["信号肽", "移位子"], "topic": "共翻译转运"},
{"type": "choice", "question": "引导新生肽链穿过内质网膜移位子的序列称为（　）",
 "options": {"A": "内在停止转移锚定序列（STA）", "B": "起始转移序列", "C": "内在信号锚定序列（SA）", "D": "KDEL序列"},
 "answer": "B",
 "explanation": "起始转移序列是引导新生肽链穿过内质网膜移位子的序列，蛋白质N端的信号肽可视为其一种；其与停止转移序列终止穿膜的作用相反。",
 "difficulty": 2, "tags": ["起始转移序列", "跨膜蛋白"], "topic": "共翻译转运"},
{"type": "choice", "question": "内在停止转移锚定序列（STA）的特点是（　）",
 "options": {"A": "与内质网膜具有强亲和力，且常位于多肽内部", "B": "位于蛋白质N端", "C": "亲水性氨基酸组成", "D": "仅存在于分泌蛋白中"},
 "answer": "A",
 "explanation": "STA是终止多肽向内质网膜转运的疏水性序列，与内质网膜具有强亲和力且常位于多肽内部，进入转运通道时发出“停止”信号使肽链停止穿膜并锚定在脂双层中。",
 "difficulty": 2, "tags": ["停止转移序列", "跨膜蛋白"], "topic": "共翻译转运"},
{"type": "choice", "question": "内在信号锚定序列（SA）的功能是（　）",
 "options": {"A": "兼具信号肽功能和跨膜锚定功能", "B": "仅能终止肽链转移", "C": "促进蛋白质降解", "D": "识别KDEL信号"},
 "answer": "A",
 "explanation": "SA是多肽链中兼具信号肽功能和跨膜锚定功能的疏水性序列，既能引导核糖体-新生肽链复合物至内质网，同时自身嵌入内质网膜脂双层后永久锚定。",
 "difficulty": 2, "tags": ["信号锚定序列", "跨膜蛋白"], "topic": "共翻译转运"},
{"type": "choice", "question": "仅含N端信号序列而无内在停止转移锚定序列（STA）的肽链，其命运是（　）",
 "options": {"A": "肽链完全进入内质网腔，形成可溶性蛋白", "B": "锚定在膜上形成膜蛋白", "C": "在细胞质基质中降解", "D": "返回细胞核"},
 "answer": "A",
 "explanation": "序列组合决定蛋白质定位与类型：仅含N端信号序列、无STA的肽链完全进入内质网腔，最终成为可溶性蛋白（如分泌蛋白）；含STA则成为膜蛋白。",
 "difficulty": 2, "tags": ["跨膜蛋白", "拓扑学"], "topic": "共翻译转运"},
{"type": "choice", "question": "下列属于I型单次跨膜蛋白实例的是（　）",
 "options": {"A": "LDL受体", "B": "转铁蛋白受体", "C": "细胞色素P450", "D": "葡糖转运蛋白"},
 "answer": "A",
 "explanation": "I型单次跨膜蛋白含可切割的N端信号序列+STA，实例包括LDL受体、流感病毒血凝素、胰岛素受体；转铁蛋白受体为II型，细胞色素P450为III型。",
 "difficulty": 2, "tags": ["跨膜蛋白", "I型"], "topic": "共翻译转运"},
{"type": "choice", "question": "下列属于II型单次跨膜蛋白实例的是（　）",
 "options": {"A": "胰岛素受体", "B": "转铁蛋白受体", "C": "细胞色素P450", "D": "G蛋白偶联受体"},
 "answer": "B",
 "explanation": "II型单次跨膜蛋白无切割型N端信号序列、含SA、N端含正电，N端亲水区朝向细胞质基质，实例包括无唾液酸糖蛋白受体和转铁蛋白受体。",
 "difficulty": 3, "tags": ["跨膜蛋白", "II型"], "topic": "共翻译转运"},
{"type": "choice", "question": "下列属于III型单次跨膜蛋白实例的是（　）",
 "options": {"A": "细胞色素P450", "B": "LDL受体", "C": "无唾液酸糖蛋白受体", "D": "电压门控Ca2+通道"},
 "answer": "A",
 "explanation": "III型单次跨膜蛋白无切割型N端信号序列、近N端含疏水跨膜片段，拓扑取向与I型相同（N端朝向内质网腔），实例为细胞色素P450。",
 "difficulty": 3, "tags": ["跨膜蛋白", "III型"], "topic": "共翻译转运"},
{"type": "choice", "question": "下列属于IV型多次跨膜蛋白实例的是（　）",
 "options": {"A": "G蛋白偶联受体", "B": "胰岛素受体", "C": "流感病毒血凝素", "D": "转铁蛋白受体"},
 "answer": "A",
 "explanation": "IV型多次跨膜蛋白含多个起始转移序列和多个STA，肽链多次穿膜，实例包括G蛋白偶联受体、葡糖转运蛋白和电压门控Ca2+通道。",
 "difficulty": 2, "tags": ["跨膜蛋白", "IV型"], "topic": "共翻译转运"},
{"type": "choice", "question": "多次跨膜蛋白的形成取决于（　）",
 "options": {"A": "多个起始转移序列与多个内在停止转移锚定序列的组合", "B": "单个信号肽", "C": "KDEL信号", "D": "SRP的数量"},
 "answer": "A",
 "explanation": "含多个起始转移序列和多个内在停止转移锚定序列（STA）的肽链可多次跨膜，形成多次跨膜蛋白。",
 "difficulty": 2, "tags": ["跨膜蛋白", "拓扑学"], "topic": "共翻译转运"},
{"type": "choice", "question": "线粒体基质蛋白输入的第一步是（　）",
 "options": {"A": "前体蛋白与分子伴侣Hsp70结合保持未折叠状态", "B": "基质靶向序列被切除", "C": "与Tim23/17结合", "D": "蛋白质折叠成活性形式"},
 "answer": "A",
 "explanation": "前体蛋白在细胞质基质游离核糖体上合成后，首先与分子伴侣Hsp70结合，保持未折叠或部分折叠状态，其N端具有线粒体基质靶向序列。",
 "difficulty": 1, "tags": ["线粒体", "翻译后转运"], "topic": "翻译后转运"},
{"type": "choice", "question": "线粒体基质蛋白输入后，基质靶向序列的处置是（　）",
 "options": {"A": "被基质蛋白酶切除", "B": "保留在蛋白N端参与折叠", "C": "插入内膜形成跨膜区", "D": "被磷酸化修饰"},
 "answer": "A",
 "explanation": "输入的蛋白质进入线粒体基质后，基质靶向序列被切除，同时Hsp70从新输入的基质蛋白上释放下来，蛋白质折叠成活性形式完成其功能。",
 "difficulty": 2, "tags": ["线粒体", "翻译后转运"], "topic": "翻译后转运"},
{"type": "choice", "question": "线粒体内膜蛋白输入途径b与途径a的主要区别是（　）",
 "options": {"A": "途径b的前体蛋白不含N端基质靶向序列", "B": "途径b蛋白具有内在疏水结构域，可被内膜蛋白Oxal识别", "C": "途径b不需要输入受体", "D": "途径b直接穿过外膜进入膜间隙"},
 "answer": "B",
 "explanation": "途径b的内膜蛋白除与途径a相同的N端基质靶向序列、输入受体和孔道外，还具有内在疏水结构域，可被内膜蛋白Oxal识别，前体先进入基质、切割后再装配到内膜上。",
 "difficulty": 3, "tags": ["线粒体", "内膜蛋白"], "topic": "翻译后转运"},
{"type": "choice", "question": "线粒体膜间隙蛋白输入途径c中，含多个内在靶向序列的蛋白被下列哪组受体识别（　）",
 "options": {"A": "Tom70/Tom22", "B": "Tom20/22", "C": "Tim23/17", "D": "Oxal"},
 "answer": "A",
 "explanation": "途径c不含N端基质靶向序列，但含多个被Tom70/Tom22识别的内在靶向序列，膜间隙蛋白Tim9/Tim10作为分子伴侣协助输入蛋白在外膜与内膜通道之间转运。",
 "difficulty": 3, "tags": ["线粒体", "膜间隙蛋白"], "topic": "翻译后转运"},
{"type": "choice", "question": "线粒体膜间隙蛋白输入途径a的实例是（　）",
 "options": {"A": "细胞色素b2", "B": "细胞色素c", "C": "ATP合成酶", "D": "转铁蛋白受体"},
 "answer": "A",
 "explanation": "途径a与内膜蛋白途径a类似，主要区别在于蛋白质（如细胞色素b2）的内在靶向序列定位在膜间隙，转运过程中被内膜上的蛋白酶切割，释放的蛋白质折叠并与血红素结合。",
 "difficulty": 3, "tags": ["线粒体", "膜间隙蛋白"], "topic": "翻译后转运"},
{"type": "choice", "question": "线粒体膜间隙蛋白输入途径b的特点是（　）",
 "options": {"A": "转运的蛋白质经外膜Tom40输入孔直接进入膜间隙", "B": "必须经过内膜蛋白酶切割", "C": "依赖Oxal识别", "D": "需要基质靶向序列"},
 "answer": "A",
 "explanation": "途径b的蛋白质通过外膜Tom40输入孔直接进入膜间隙，这一途径不涉及内膜上的蛋白酶切割。",
 "difficulty": 3, "tags": ["线粒体", "膜间隙蛋白"], "topic": "翻译后转运"},
{"type": "choice", "question": "叶绿体基质蛋白输入时前体蛋白的状态是（　）",
 "options": {"A": "以非折叠形式输入叶绿体基质", "B": "以完全折叠的天然构象输入", "C": "与膜泡结合后输入", "D": "先经高尔基体加工"},
 "answer": "A",
 "explanation": "核基因编码的叶绿体基质蛋白在细胞质基质中合成后具有N端基质输入序列，这些前体蛋白以非折叠形式输入叶绿体基质，转运依赖基质Hsp70和ATP。",
 "difficulty": 2, "tags": ["叶绿体", "翻译后转运"], "topic": "翻译后转运"},
{"type": "choice", "question": "类囊体蛋白分选的SRP传导途径的实例是（　）",
 "options": {"A": "质体蓝素蛋白", "B": "金属结合蛋白", "C": "核酮糖-1,5-二磷酸羧化酶", "D": "细胞色素b2"},
 "answer": "A",
 "explanation": "质体蓝素蛋白前体在基质中保持非折叠态，与叶绿体SRP结合，在叶绿体SRP受体和转运蛋白SecY介导下进入类囊体腔，之后类囊体靶向序列被切除。",
 "difficulty": 3, "tags": ["叶绿体", "类囊体蛋白"], "topic": "翻译后转运"},
{"type": "choice", "question": "类囊体蛋白分选的pH依赖途径进入类囊体腔的关键是（　）",
 "options": {"A": "类囊体靶向序列N端精氨酸残基和跨内膜pH梯度", "B": "SRP介导", "C": "SecY转运蛋白", "D": "GTP水解供能"},
 "answer": "A",
 "explanation": "pH依赖途径中，类囊体靶向序列N端精氨酸残基和跨内膜pH梯度是其进入类囊体腔的关键，膜上特定转运蛋白协助其进入，进入后靶向序列切除、蛋白成熟。",
 "difficulty": 3, "tags": ["叶绿体", "类囊体蛋白"], "topic": "翻译后转运"},
# ---- truefalse 9 ----
{"type": "truefalse", "question": "蛋白质分选仅存在于特化的分泌细胞中。",
 "answer": "false",
 "explanation": "蛋白质分选普遍存在于所有真核细胞中，是细胞维持正常结构和功能的基础，并非分泌细胞特有。",
 "difficulty": 1, "tags": ["蛋白质分选"], "topic": "蛋白质分选"},
{"type": "truefalse", "question": "细胞质基质中的可溶性驻留蛋白和骨架蛋白经翻译后转运途径定位。",
 "answer": "true",
 "explanation": "翻译后转运途径的蛋白质可在细胞质基质游离核糖体上完成合成后，成为细胞质基质中的可溶性驻留蛋白和骨架蛋白。",
 "difficulty": 2, "tags": ["翻译后转运"], "topic": "翻译后转运"},
{"type": "truefalse", "question": "信号肽被切除后立即被快速降解。",
 "answer": "true",
 "explanation": "内质网腔面的信号肽酶切除信号肽后将其快速降解，信号肽不会进入内质网腔。",
 "difficulty": 1, "tags": ["信号肽", "共翻译转运"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "多肽链合成折叠完成后，核糖体从内质网膜释放，移位子通道关闭。",
 "answer": "true",
 "explanation": "多肽链合成折叠完成后，核糖体从内质网膜上释放，移位子通道关闭，转运过程终止。",
 "difficulty": 1, "tags": ["移位子", "共翻译转运"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "起始转移序列与停止转移序列对穿膜的作用相反。",
 "answer": "true",
 "explanation": "起始转移序列能启动穿膜，与停止转移序列终止穿膜的作用相反；两者配合决定跨膜蛋白的拓扑学特征。",
 "difficulty": 2, "tags": ["起始转移序列", "停止转移序列"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "内在信号锚定序列（SA）嵌入内质网膜脂双层后永久锚定。",
 "answer": "true",
 "explanation": "SA既能引导核糖体-新生肽链复合物至内质网，同时其自身嵌入内质网膜脂双层后永久锚定，兼具信号肽和跨膜锚定功能。",
 "difficulty": 2, "tags": ["信号锚定序列"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "I型单次跨膜蛋白的N端亲水区朝向内质网腔。",
 "answer": "true",
 "explanation": "I型单次跨膜蛋白含可切割的N端信号序列+STA，N端亲水区朝向内质网腔，C端亲水区朝向细胞质基质。",
 "difficulty": 2, "tags": ["跨膜蛋白", "拓扑学"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "跨膜片段侧翼带负电荷的氨基酸残基一侧通常朝向细胞质基质。",
 "answer": "false",
 "explanation": "带正电荷的氨基酸残基一侧通常朝向细胞质基质，这决定跨膜蛋白的拓扑取向；负电荷侧翼通常朝向内质网腔。",
 "difficulty": 2, "tags": ["跨膜蛋白", "拓扑学"], "topic": "共翻译转运"},
{"type": "truefalse", "question": "线粒体基质靶向序列在蛋白质进入基质后被切除。",
 "answer": "true",
 "explanation": "输入的蛋白质在基质中，基质靶向序列被切除，同时Hsp70从新输入的基质蛋白上释放下来，蛋白质再折叠成活性形式。",
 "difficulty": 2, "tags": ["线粒体", "翻译后转运"], "topic": "翻译后转运"},
]

for q in NEW:
    q['id'] = len(qs) + 1
    qs.append(q)

json.dump(qs, open(P, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('第六章批次1落盘，当前总数:', len(qs))
