# -*- coding: utf-8 -*-
"""第十六章 生物能学 题目数据 C 组:Q73-Q106(呼吸链排列、电子传递与ATP生成)"""

QC = [
{
 "topic": "呼吸链的排列顺序",
 "type": "choice",
 "question": "NADH进入呼吸链的入口是?",
 "options": {"A": "复合体I(NADH-泛醌还原酶)", "B": "复合体II(琥珀酸-泛醌还原酶)", "C": "复合体III(泛醌-细胞色素c还原酶)", "D": "复合体IV(细胞色素c氧化酶)"},
 "answer": "A",
 "explanation": "NADH在复合体I(NADH-泛醌还原酶)处脱氢,电子经FMN、Fe-S传给CoQ进入呼吸链;这是NADH氧化链与FADH2氧化链产能差异的根源。",
 "difficulty": 1, "tags": ["呼吸链", "NADH", "进入点", "复合体I", "考纲39"],
},
{
 "topic": "呼吸链的排列顺序",
 "type": "choice",
 "question": "FADH2(如琥珀酸脱氢产生的)进入呼吸链的入口是?",
 "options": {"A": "复合体II(琥珀酸-泛醌还原酶)", "B": "复合体I(NADH-泛醌还原酶)", "C": "复合体IV(细胞色素c氧化酶)", "D": "F0F1-ATP合酶"},
 "answer": "A",
 "explanation": "FADH2在复合体II(琥珀酸-泛醌还原酶)处将电子经FAD、Fe-S传给CoQ进入呼吸链,因绕过了复合体I,故少一个偶联部位,产能少于NADH。",
 "difficulty": 1, "tags": ["呼吸链", "FADH2", "进入点", "复合体II", "考纲39"],
},
{
 "topic": "递氢体与递电子体",
 "type": "multi",
 "question": "呼吸链中属于递氢体(同时传递质子和电子)的有?(多选)",
 "options": {"A": "NAD+(NADH)", "B": "FAD(FADH2)", "C": "FMN(FMNH2)", "D": "辅酶Q(CoQ)", "E": "细胞色素c"},
 "answer": "ABCD",
 "explanation": "递氢体同时传递质子和电子,包括NAD、FAD、FMN、CoQ;细胞色素和铁硫蛋白只传递电子,属递电子体而非递氢体(递氢体同时是递电子体,反之不然)。",
 "difficulty": 2, "tags": ["递氢体", "NAD", "FAD", "FMN", "CoQ", "考纲39"],
},
{
 "topic": "呼吸链的排列顺序",
 "type": "choice",
 "question": "NADH氧化呼吸链中电子传递的排列顺序是?",
 "options": {"A": "NADH→复合体I→CoQ→复合体III→Cyt c→复合体IV→O2", "B": "NADH→复合体II→CoQ→复合体III→Cyt c→复合体IV→O2", "C": "NADH→CoQ→复合体I→Cyt c→复合体III→复合体IV→O2", "D": "NADH→复合体IV→复合体III→CoQ→Cyt c→复合体I→O2"},
 "answer": "A",
 "explanation": "NADH氧化呼吸链:NADH→复合体I(FMN、Fe-S)→CoQ→复合体III(Cyt b→c1)→Cyt c→复合体IV(Cyt a→a3)→O2;电子按氧化还原电位由低到高传递。",
 "difficulty": 2, "tags": ["呼吸链", "排列顺序", "NADH链", "考纲39"],
},
{
 "topic": "呼吸链的排列顺序",
 "type": "choice",
 "question": "呼吸链中细胞色素传递电子的排列顺序是?",
 "options": {"A": "Cyt b→Cyt c1→Cyt c→Cyt a→Cyt a3", "B": "Cyt a3→Cyt a→Cyt c→Cyt c1→Cyt b", "C": "Cyt c→Cyt b→Cyt c1→Cyt a→Cyt a3", "D": "Cyt b→Cyt a→Cyt a3→Cyt c1→Cyt c"},
 "answer": "A",
 "explanation": "细胞色素按氧化还原电位由低到高的排列顺序为:Cyt b→Cyt c1→Cyt c→Cyt a→Cyt a3,其中Cyt a3是电子传给O2的部位。",
 "difficulty": 2, "tags": ["细胞色素", "排列顺序", "考纲39"],
},
{
 "topic": "呼吸链的排列顺序",
 "type": "truefalse",
 "question": "FADH2氧化呼吸链与NADH氧化呼吸链一样,都经过3个偶联部位生成ATP。",
 "answer": "false",
 "explanation": "FADH2在复合体II进入呼吸链,绕过了复合体I,故只经过复合体III、IV两个偶联部位,生成ATP数少于NADH(NADH约2.5个,琥珀酸FADH2约1.5个ATP)。",
 "difficulty": 2, "tags": ["FADH2链", "偶联部位", "考纲39"],
},
{
 "topic": "呼吸链排列顺序的实验依据",
 "type": "choice",
 "question": "呼吸链中各传递体排列顺序的主要依据是?",
 "options": {"A": "按标准氧化还原电位由低到高排列,电子从电位低的成员传向电位高的成员", "B": "按分子量由小到大排列", "C": "按发现的先后顺序排列", "D": "按含量多少排列"},
 "answer": "A",
 "explanation": "呼吸链各成员按标准氧化还原电位(E0')由低到高排列,电子沿电位升高方向传递(NADH约-0.32V→O2约+0.82V),电位差提供自由能驱动ATP合成。",
 "difficulty": 2, "tags": ["呼吸链", "排列依据", "氧化还原电位", "考纲39"],
},
{
 "topic": "呼吸链排列顺序的实验依据",
 "type": "truefalse",
 "question": "电子沿呼吸链从氧化还原电位高的成员传向电位低的成员。",
 "answer": "false",
 "explanation": "电子沿呼吸链从氧化还原电位低的成员(如NADH,约-0.32V)传向电位高的成员(如O2,约+0.82V),电位差越大,释放自由能越多。",
 "difficulty": 2, "tags": ["呼吸链", "氧化还原电位", "传递方向", "考纲39"],
},
{
 "topic": "电子传递抑制剂",
 "type": "choice",
 "question": "鱼藤酮、异戊巴比妥(安密妥)、杀粉蝶菌素抑制呼吸链的部位是?",
 "options": {"A": "复合体I,阻断电子从NADH向CoQ的传递", "B": "复合体II,阻断琥珀酸脱氢", "C": "复合体III,阻断Cyt b→Cyt c1", "D": "复合体IV,阻断Cyt aa3→O2"},
 "answer": "A",
 "explanation": "鱼藤酮、异戊巴比妥、杀粉蝶菌素抑制复合体I(NADH-泛醌还原酶),阻断电子从NADH经FMN向CoQ的传递;此时FADH2氧化不受影响。",
 "difficulty": 2, "tags": ["抑制剂", "鱼藤酮", "复合体I", "考纲39"],
},
{
 "topic": "电子传递抑制剂",
 "type": "choice",
 "question": "抗霉素A抑制呼吸链的部位是?",
 "options": {"A": "复合体III,阻断电子在Cyt b→Cyt c1之间的传递", "B": "复合体I,阻断NADH→CoQ", "C": "复合体II,阻断琥珀酸→CoQ", "D": "复合体IV,阻断Cyt aa3→O2"},
 "answer": "A",
 "explanation": "抗霉素A抑制复合体III(泛醌-细胞色素c还原酶),阻断电子在细胞色素b与c1之间的传递,使CoQ处于还原状态、Cyt c1处于氧化状态。",
 "difficulty": 2, "tags": ["抑制剂", "抗霉素A", "复合体III", "考纲39"],
},
{
 "topic": "电子传递抑制剂",
 "type": "choice",
 "question": "氰化物(CN-)、一氧化碳(CO)、叠氮化物(N3-)抑制呼吸链的部位是?",
 "options": {"A": "复合体IV(细胞色素c氧化酶),阻断电子从Cyt aa3传给O2", "B": "复合体I(NADH-泛醌还原酶)", "C": "复合体II(琥珀酸-泛醌还原酶)", "D": "F0F1-ATP合酶"},
 "answer": "A",
 "explanation": "CN-、CO、N3-、H2S与复合体IV(细胞色素c氧化酶)的Cyt aa3结合,阻断电子传给O2,使整个呼吸链瘫痪,细胞因不能利用氧而窒息,故氧化物剧毒。",
 "difficulty": 2, "tags": ["抑制剂", "氰化物", "复合体IV", "考纲39"],
},
{
 "topic": "电子传递抑制剂",
 "type": "multi",
 "question": "下列抑制剂与其抑制部位对应正确的有?(多选)(985真题风格)",
 "options": {"A": "鱼藤酮——复合体I(NADH→CoQ)", "B": "抗霉素A——复合体III(Cyt b→Cyt c1)", "C": "氰化物、CO——复合体IV(Cyt aa3→O2)", "D": "2,4-二硝基苯酚——复合体I", "E": "萎锈灵——复合体II(琥珀酸脱氢)"},
 "answer": "ABCE",
 "explanation": "鱼藤酮/安密妥/杀粉蝶菌素抑制复合体I;萎锈灵抑制复合体II;抗霉素A抑制复合体III;CN-、CO、N3-、H2S抑制复合体IV;DNP是解偶联剂,不抑制某特定复合体的电子传递,而是消除质子梯度。",
 "difficulty": 3, "tags": ["抑制剂", "作用部位", "985真题风格", "考纲39"],
},
{
 "topic": "呼吸链复合体",
 "type": "truefalse",
 "question": "呼吸链复合体II没有质子泵功能。",
 "answer": "true",
 "explanation": "复合体II(琥珀酸-泛醌还原酶)只催化电子从琥珀酸传给CoQ,不泵出质子,其氧化还原电位差也不足以偶联ATP合成,故不是偶联部位。",
 "difficulty": 2, "tags": ["复合体II", "质子泵", "考纲39"],
},
{
 "topic": "呼吸链的排列顺序",
 "type": "short",
 "question": "写出线粒体中从NADH到O2的电子传递链(呼吸链)各组分的排列顺序。",
 "answer": "①NADH→复合体I(FMN、Fe-S)→辅酶Q(CoQ)→复合体III(Cyt b→Cyt c1)→Cyt c→复合体IV(Cyt a→Cyt a3)→O2;②FADH2(琥珀酸脱氢)从复合体II进入:琥珀酸→复合体II(FAD)→CoQ→复合体III→Cyt c→复合体IV→O2;③电子按标准氧化还原电位由低到高传递,最终与O2结合生成水。",
 "explanation": "写出NADH氧化呼吸链排列顺序是呼吸链部分的标志性简答/填空考点,需同时掌握FADH2链的汇入点(复合体II)。",
 "difficulty": 2, "tags": ["呼吸链", "排列顺序", "简答", "考纲39"],
},
{
 "topic": "呼吸链排列顺序的实验依据",
 "type": "short",
 "question": "呼吸链各组分的排列顺序是通过哪些实验方法确定的?",
 "answer": "①标准氧化还原电位测定:各组分按E0'由低到高排列,电子自电位低者传向电位高者;②吸收光谱法:用分光光度法观察缓慢给氧时各组分的氧化顺序;③特异阻断剂实验:用呼吸链抑制剂阻断特定环节,根据阻断前后各组分的氧化还原状态推断相对位置;④体外重组实验:拆开并重组呼吸链,鉴定各复合体的组成与传递次序。",
 "explanation": "考查呼吸链排列顺序的四种实验依据(氧化还原电位、吸收光谱、特异阻断剂、重组实验),属考纲39\"排列顺序\"的深层次考点。",
 "difficulty": 3, "tags": ["呼吸链", "实验依据", "简答", "考纲39"],
},
# ============ E. 电子传递过程与ATP的生成(考纲38,教材补全) ============
{
 "topic": "氧化磷酸化",
 "type": "choice",
 "question": "氧化磷酸化是指?",
 "options": {"A": "代谢物氧化(电子经呼吸链传递)释放的能量与ADP磷酸化生成ATP相偶联的过程", "B": "底物分子内高能键直接转移给ADP生成ATP的过程", "C": "光能驱动ADP磷酸化的过程", "D": "ATP水解释放能量的过程"},
 "answer": "A",
 "explanation": "氧化磷酸化指电子沿呼吸链传递(氧化)过程中释放的能量驱动ADP+Pi合成ATP(磷酸化)的过程,两者紧密偶联;底物高能键直接转移给ADP称底物水平磷酸化。",
 "difficulty": 1, "tags": ["氧化磷酸化", "定义", "考纲38"],
},
{
 "topic": "氧化磷酸化",
 "type": "choice",
 "question": "氧化磷酸化的偶联部位(能释放足够自由能偶联ATP合成的部位)共有几处?",
 "options": {"A": "3处,即复合体I、III、IV", "B": "4处,即复合体I、II、III、IV", "C": "2处,即复合体I、IV", "D": "1处,即复合体IV"},
 "answer": "A",
 "explanation": "偶联部位在复合体I(NADH→CoQ)、复合体III(CoQ→Cyt c)、复合体IV(Cyt aa3→O2)3处;复合体II电位差太小,不能偶联ATP合成。",
 "difficulty": 2, "tags": ["氧化磷酸化", "偶联部位", "考纲38"],
},
{
 "topic": "氧化磷酸化",
 "type": "truefalse",
 "question": "复合体II(琥珀酸-泛醌还原酶)是氧化磷酸化的偶联部位。",
 "answer": "false",
 "explanation": "复合体II的氧化还原电位差不足以偶联ATP合成,且无质子泵功能,不是偶联部位;这就是FADH2氧化只生成约1.5个ATP而NADH氧化生成约2.5个ATP的原因。",
 "difficulty": 2, "tags": ["氧化磷酸化", "复合体II", "偶联部位", "考纲38"],
},
{
 "topic": "P/O比值",
 "type": "choice",
 "question": "按朱圣庚第四版教材,NADH氧化呼吸链的P/O比值约为?",
 "options": {"A": "2.5", "B": "1.5", "C": "3.5", "D": "4.0"},
 "answer": "A",
 "explanation": "P/O比指每消耗1 mol氧原子所合成的ATP摩尔数;NADH氧化呼吸链约合成2.5个ATP(P/O≈2.5),FADH2氧化呼吸链约1.5个ATP(P/O≈1.5)。",
 "difficulty": 2, "tags": ["P/O比", "NADH", "ATP产量", "考纲38"],
},
{
 "topic": "NADH与FADH2的产能差异",
 "type": "choice",
 "question": "NADH经呼吸链氧化比FADH2(琥珀酸氧化)多生成ATP,其根本原因是?",
 "options": {"A": "NADH经3个偶联部位,而FADH2经2个偶联部位", "B": "NADH分子中含有更多磷", "C": "FADH2不能把电子传给氧", "D": "NADH比FADH2的分子量更大"},
 "answer": "A",
 "explanation": "NADH在复合体I进入呼吸链,经复合体I、III、IV三个偶联部位;FADH2在复合体II进入,绕过复合体I,只经2个偶联部位,故产能少约1个ATP(2.5 vs 1.5)。",
 "difficulty": 2, "tags": ["NADH", "FADH2", "偶联部位", "产能差异", "考纲38"],
},
{
 "topic": "底物水平磷酸化",
 "type": "choice",
 "question": "底物水平磷酸化是指?",
 "options": {"A": "代谢物分子内的高能键(高能磷酸基团)直接转移给ADP生成ATP的过程", "B": "电子经呼吸链传递偶联ATP合成的过程", "C": "光能驱动ADP磷酸化的过程", "D": "质子梯度驱动ATP合成的过程"},
 "answer": "A",
 "explanation": "底物水平磷酸化是代谢物分子内高能键直接转移给ADP生成ATP的过程,不需氧、不需呼吸链,如糖酵解中1,3-二磷酸甘油酸→3-磷酸甘油酸时生成ATP。",
 "difficulty": 1, "tags": ["底物水平磷酸化", "定义", "考纲38"],
},
{
 "topic": "底物水平磷酸化",
 "type": "choice",
 "question": "下列过程中属于底物水平磷酸化的是?",
 "options": {"A": "1,3-二磷酸甘油酸将高能磷酰基转移给ADP生成3-磷酸甘油酸和ATP", "B": "NADH经呼吸链氧化偶联ATP合成", "C": "琥珀酸脱氢生成延胡索酸", "D": "葡萄糖磷酸化生成6-磷酸葡萄糖"},
 "answer": "A",
 "explanation": "1,3-二磷酸甘油酸→3-磷酸甘油酸(糖酵解)及磷酸烯醇式丙酮酸→丙酮酸是底物水平磷酸化的典型例子;NADH氧化偶联ATP合成是氧化磷酸化;葡萄糖磷酸化消耗ATP,不是产能过程。",
 "difficulty": 2, "tags": ["底物水平磷酸化", "举例", "考纲38"],
},
{
 "topic": "底物水平磷酸化与氧化磷酸化的比较",
 "type": "multi",
 "question": "关于底物水平磷酸化与氧化磷酸化的区别,下列说法正确的有?(多选)",
 "options": {"A": "底物水平磷酸化由代谢物高能键直接转移给ADP生成ATP,不需氧和呼吸链", "B": "氧化磷酸化由电子传递释放的能量偶联ATP合成,在线粒体内膜进行", "C": "机体ATP的主要来源是氧化磷酸化", "D": "两者都需要完整的线粒体内膜", "E": "红细胞(无氧酵解)靠底物水平磷酸化供能"},
 "answer": "ABCE",
 "explanation": "底物水平磷酸化不需氧和呼吸链,胞浆、线粒体均可发生,是红细胞及缺氧组织的能量来源;氧化磷酸化在线粒体内膜进行,是机体ATP的主要来源;只有氧化磷酸化依赖完整的线粒体内膜。",
 "difficulty": 3, "tags": ["底物水平磷酸化", "氧化磷酸化", "比较", "考纲38"],
},
{
 "topic": "ATP的来源",
 "type": "truefalse",
 "question": "机体细胞ATP的主要生成方式是底物水平磷酸化。",
 "answer": "false",
 "explanation": "机体ATP的主要来源是氧化磷酸化(约90%),底物水平磷酸化仅在糖酵解等少数步骤及缺氧、红细胞等特殊情况下起重要作用。",
 "difficulty": 2, "tags": ["ATP来源", "氧化磷酸化", "考纲38"],
},
{
 "topic": "NADH的穿梭",
 "type": "choice",
 "question": "胞质中NADH经苹果酸-天冬氨酸穿梭进入线粒体氧化,约可生成多少ATP?(朱圣庚第四版口径)",
 "options": {"A": "约2.5个ATP", "B": "约1.5个ATP", "C": "约3个ATP", "D": "不生成ATP"},
 "answer": "A",
 "explanation": "胞质NADH不能直接透过线粒体内膜,须经穿梭系统进入;苹果酸-天冬氨酸穿梭(肝、心肌等)转入的NADH约生成2.5个ATP,α-磷酸甘油穿梭(脑、骨骼肌)转入的NADH约生成1.5个ATP。",
 "difficulty": 3, "tags": ["穿梭", "苹果酸-天冬氨酸", "NADH", "考纲38"],
},
{
 "topic": "NADH的穿梭",
 "type": "choice",
 "question": "脑和骨骼肌细胞中,胞质NADH经α-磷酸甘油穿梭进入线粒体氧化,约可生成多少ATP?(朱圣庚第四版口径)",
 "options": {"A": "约1.5个ATP", "B": "约2.5个ATP", "C": "约4个ATP", "D": "约0.5个ATP"},
 "answer": "A",
 "explanation": "α-磷酸甘油穿梭(脑、骨骼肌)把胞质NADH的还原当量转入线粒体生成FADH2,经复合体II进入呼吸链,只经2个偶联部位,约生成1.5个ATP。",
 "difficulty": 3, "tags": ["穿梭", "α-磷酸甘油", "FADH2", "考纲38"],
},
{
 "topic": "电子传递与ATP生成",
 "type": "short",
 "question": "为什么FADH2(如琥珀酸氧化产生的)经呼吸链氧化生成的ATP比NADH少?",
 "answer": "①NADH在复合体I进入呼吸链,经复合体I、III、IV三个偶联部位,约生成2.5个ATP;②FADH2在复合体II进入呼吸链,绕过了复合体I,只经复合体III、IV两个偶联部位;③因此FADH2氧化约只生成1.5个ATP,比NADH少约1个ATP。",
 "explanation": "从进入点与偶联部位数解释NADH与FADH2产能差异,是考纲38\"电子传递过程与ATP生成\"的高频简答。",
 "difficulty": 2, "tags": ["FADH2", "NADH", "偶联部位", "简答", "考纲38"],
},
{
 "topic": "NADH链与FADH2链的比较",
 "type": "multi",
 "question": "关于NADH氧化呼吸链与琥珀酸(FADH2)氧化呼吸链的比较,下列说法正确的有?(多选)",
 "options": {"A": "NADH链从复合体I进入,FADH2链从复合体II进入", "B": "NADH链经过3个偶联部位,FADH2链经过2个偶联部位", "C": "NADH链约生成2.5个ATP,FADH2链约生成1.5个ATP", "D": "两条链共用CoQ、复合体III、复合体IV和O2", "E": "两条链生成的ATP数量完全相同"},
 "answer": "ABCD",
 "explanation": "两条链的异同:进入点不同(复合体I vs II)、偶联部位数不同(3 vs 2)、产能不同(2.5 vs 1.5);自CoQ之后共用复合体III、Cyt c、复合体IV及最终受体O2。",
 "difficulty": 3, "tags": ["NADH链", "FADH2链", "比较", "考纲38"],
},
{
 "topic": "底物水平磷酸化与氧化磷酸化的比较",
 "type": "short",
 "question": "简述底物水平磷酸化与氧化磷酸化两种ATP生成方式的区别。",
 "answer": "①能量来源不同:底物水平磷酸化来自代谢物分子内高能键的直接转移;氧化磷酸化来自电子沿呼吸链传递释放的自由能;②发生部位不同:底物水平磷酸化在胞浆和线粒体基质中进行;氧化磷酸化在线粒体内膜上进行;③对氧和呼吸链的依赖不同:底物水平磷酸化不需氧、不需呼吸链;氧化磷酸化必须经呼吸链并以氧为最终电子受体;④重要性不同:氧化磷酸化是机体ATP的主要来源,底物水平磷酸化在无氧(如红细胞)和缺氧情况下尤为重要。",
 "explanation": "从能量来源、部位、需氧性、重要性四方面比较两种磷酸化方式,属考纲38核心简答考点。",
 "difficulty": 2, "tags": ["底物水平磷酸化", "氧化磷酸化", "比较", "简答", "考纲38"],
},
{
 "topic": "电子传递与能量释放",
 "type": "choice",
 "question": "电子沿呼吸链传递所释放的能量,其最主要去向是?",
 "options": {"A": "用于泵出质子建立跨内膜质子梯度,驱动ATP合成", "B": "全部以热能形式散失", "C": "用于合成蛋白质", "D": "用于DNA复制"},
 "answer": "A",
 "explanation": "呼吸链传递电子时,偶联部位(复合体I、III、IV)释放的自由能用于将H+从基质泵到膜间隙,建立跨内膜电化学梯度(质子动力势),质子顺梯度回流驱动ATP合成;少量能量以热散失。",
 "difficulty": 2, "tags": ["电子传递", "能量去向", "质子梯度", "考纲38"],
},
{
 "topic": "氧化磷酸化",
 "type": "choice",
 "question": "氧化磷酸化的正常进行需要什么基本条件?",
 "options": {"A": "结构完整封闭的线粒体内膜(内膜对H+等不通透)", "B": "线粒体外膜完整即可", "C": "细胞核完整", "D": "内质网完整"},
 "answer": "A",
 "explanation": "氧化磷酸化依赖完整封闭的线粒体内膜:内膜既是呼吸链组分所在,又是质子泵与ATP合酶的工作界面,若内膜破损通透,质子梯度无法维持,氧化磷酸化即被破坏。",
 "difficulty": 2, "tags": ["氧化磷酸化", "线粒体内膜", "完整性", "考纲38"],
},
{
 "topic": "氧化磷酸化的特征",
 "type": "multi",
 "question": "关于氧化磷酸化,下列说法正确的有?(多选)",
 "options": {"A": "它是电子传递与ADP磷酸化紧密偶联的过程", "B": "它发生在线粒体内膜上", "C": "它是机体产生ATP的主要途径", "D": "它可以脱离氧而单独进行", "E": "其偶联部位为复合体I、III、IV"},
 "answer": "ABCE",
 "explanation": "氧化磷酸化在线粒体内膜进行,电子传递与磷酸化偶联,偶联部位为复合体I、III、IV,是机体ATP的主要来源;电子最终必须传给O2,故不能脱离氧进行。",
 "difficulty": 2, "tags": ["氧化磷酸化", "特征", "考纲38"],
},
]
