# -*- coding: utf-8 -*-
# 第二十七章 batch3: 题 61-90 (嘌呤补救合成 / Lesch-Nyhan / 嘧啶从头合成 / 核苷酸合成调节)
QUESTIONS = [
{
 "id": 61,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "choice",
 "question": "下列哪些组织主要依靠嘌呤核苷酸的补救合成途径?",
 "options": {"A": "脑、骨髓等", "B": "肝脏、肾脏", "C": "骨骼肌、心肌", "D": "红细胞、白细胞"},
 "answer": "A",
 "explanation": "脑、骨髓等组织缺乏从头合成核苷酸的酶系,主要利用补救合成途径获得嘌呤核苷酸;肝脏等组织则以从头合成为主。",
 "difficulty": 1,
 "tags": ["补救合成", "脑", "骨髓"]
},
{
 "id": 62,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "choice",
 "question": "催化腺嘌呤与PRPP生成AMP的酶是?",
 "options": {"A": "腺嘌呤磷酸核糖转移酶(APRT)", "B": "次黄嘌呤-鸟嘌呤磷酸核糖转移酶(HGPRT)", "C": "腺嘌呤核苷激酶", "D": "磷酸核糖焦磷酸激酶"},
 "answer": "A",
 "explanation": "APRT催化腺嘌呤+PRPP→AMP+PPi;HGPRT催化次黄嘌呤+PRPP→IMP+PPi和鸟嘌呤+PRPP→GMP+PPi,两者是磷酸核糖转移酶指导的补救合成途径的关键酶。",
 "difficulty": 2,
 "tags": ["APRT", "补救合成", "腺嘌呤"]
},
{
 "id": 63,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "choice",
 "question": "HGPRT(次黄嘌呤-鸟嘌呤磷酸核糖转移酶)催化合成的核苷酸是?",
 "options": {"A": "IMP和GMP", "B": "AMP和GMP", "C": "IMP和AMP", "D": "XMP和GMP"},
 "answer": "A",
 "explanation": "HGPRT催化次黄嘌呤+PRPP→IMP+PPi、鸟嘌呤+PRPP→GMP+PPi,即同时催化生成IMP和GMP,是嘌呤补救合成途径的关键酶。",
 "difficulty": 2,
 "tags": ["HGPRT", "IMP", "GMP"]
},
{
 "id": 64,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "choice",
 "question": "嘌呤碱与1-磷酸核糖在核苷磷酸化酶作用下生成核苷后,进一步生成核苷酸的磷酸供体是?",
 "options": {"A": "ATP", "B": "GTP", "C": "UTP", "D": "磷酸肌酸"},
 "answer": "A",
 "explanation": "核苷在适当的磷酸激酶作用下,由ATP提供磷酸基团形成核苷酸;但由于缺乏除腺嘌呤核苷激酶以外的嘌呤核苷激酶,这种补救方式并不普遍。",
 "difficulty": 2,
 "tags": ["核苷磷酸化酶", "磷酸激酶", "ATP"]
},
{
 "id": 65,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "truefalse",
 "question": "嘌呤核苷酸补救合成途径耗能少、过程简单,可减少能量和氨基酸的消耗。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "A",
 "explanation": "补救合成利用游离的嘌呤或嘌呤核苷,经简单反应合成嘌呤核苷酸,过程简单、耗能少,可减少能量和氨基酸消耗,弥补脑、骨髓等组织不能从头合成核苷酸的不足。",
 "difficulty": 1,
 "tags": ["补救合成", "耗能少", "意义"]
},
{
 "id": 66,
 "topic": "Lesch-Nyhan综合征",
 "type": "choice",
 "question": "Lesch-Nyhan综合征(自毁容貌症)的病因是?",
 "options": {"A": "次黄嘌呤-鸟嘌呤磷酸核糖转移酶(HGPRT)遗传缺陷", "B": "腺嘌呤磷酸核糖转移酶(APRT)缺陷", "C": "黄嘌呤氧化酶缺陷", "D": "乳清酸核苷酸脱羧酶缺陷"},
 "answer": "A",
 "explanation": "Lesch-Nyhan综合征是次黄嘌呤-鸟嘌呤磷酸核糖转移酶遗传缺陷引起的伴性遗传性疾病,表现为血高尿酸症、高度智力障碍、脑源性麻痹、自伤症等。",
 "difficulty": 2,
 "tags": ["Lesch-Nyhan", "HGPRT", "遗传缺陷"]
},
{
 "id": 67,
 "topic": "Lesch-Nyhan综合征",
 "type": "multi",
 "question": "Lesch-Nyhan综合征(自毁容貌症)的临床表现包括?",
 "options": {"A": "血高尿酸症", "B": "高度智力障碍和脑源性麻痹", "C": "自伤行为(自我咬伤)", "D": "乳清酸在血液和尿液中大量出现"},
 "answer": "ABC",
 "explanation": "Lesch-Nyhan综合征由HGPRT遗传缺陷引起,表现为血高尿酸症、高度智力障碍、脑源性麻痹、自伤症等,属伴性遗传性疾病;乳清酸尿症是嘧啶合成酶缺陷的另一疾病。",
 "difficulty": 2,
 "tags": ["Lesch-Nyhan", "高尿酸", "自伤"]
},
{
 "id": 68,
 "topic": "Lesch-Nyhan综合征",
 "type": "choice",
 "question": "HGPRT缺陷导致高尿酸血症的机制是?",
 "options": {"A": "次黄嘌呤和鸟嘌呤不能被回收为IMP和GMP,转而降解为尿酸", "B": "嘌呤从头合成途径被完全阻断", "C": "尿酸氧化酶活性升高", "D": "黄嘌呤氧化酶被激活而大量合成"},
 "answer": "A",
 "explanation": "缺乏HGPRT使次黄嘌呤和鸟嘌呤不能转换为IMP和GMP,而被降解为尿酸,过量尿酸导致高尿酸血症及痛风样症状,这是Lesch-Nyhan综合征的生化机制。",
 "difficulty": 3,
 "tags": ["HGPRT", "尿酸", "机制"]
},
{
 "id": 69,
 "topic": "嘌呤核苷酸的补救合成",
 "type": "short",
 "question": "简述嘌呤核苷酸补救合成途径的定义及生理意义。",
 "answer": "①定义:利用游离的嘌呤或嘌呤核苷,经过简单的反应过程合成嘌呤核苷酸的过程;②两种方式:核苷磷酸化酶+核苷磷酸激酶途径(不普遍),磷酸核糖转移酶(APRT、HGPRT)途径(更重要);③意义:过程简单、耗能少,减少能量和氨基酸的消耗,弥补脑、骨髓等不能从头合成嘌呤核苷酸组织的不足。",
 "explanation": "补救合成是嘌呤核苷酸合成的两条途径之一,重点考查定义、酶与生理意义(脑、骨髓组织依赖)。",
 "difficulty": 2,
 "tags": ["补救合成", "定义", "意义"]
},
{
 "id": 70,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "multi",
 "question": "关于嘧啶环从头合成的原子来源,正确的有?",
 "options": {"A": "天冬氨酸提供部分原子", "B": "谷氨酰胺参与嘧啶环的合成", "C": "CO₂是嘧啶环原子来源之一", "D": "甘氨酸是嘧啶环的重要组成部分"},
 "answer": "ABC",
 "explanation": "嘧啶环的原子来源为天冬氨酸、谷氨酰胺、CO₂,并结合5-磷酸核糖(PRPP);与嘌呤环不同,甘氨酸不参与嘧啶环的合成,故D错。",
 "difficulty": 2,
 "tags": ["嘧啶环", "原子来源", "天冬氨酸"]
},
{
 "id": 71,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "嘧啶核苷酸从头合成过程中,氨基甲酰磷酸与天冬氨酸结合生成的中间物是?",
 "options": {"A": "氨基甲酰天冬氨酸", "B": "二氢乳清酸", "C": "乳清酸", "D": "乳清酸核苷酸(OMP)"},
 "answer": "A",
 "explanation": "氨基甲酰磷酸与天冬氨酸在ATCase(天冬氨酸转氨甲酰酶)催化下结合生成氨基甲酰天冬氨酸,再经闭环、氧化生成二氢乳清酸、乳清酸,乳清酸与PRPP结合生成OMP,脱羧生成UMP。",
 "difficulty": 2,
 "tags": ["氨基甲酰天冬氨酸", "嘧啶合成", "中间物"]
},
{
 "id": 72,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "嘧啶核苷酸从头合成中,乳清酸与PRPP反应生成的产物是?",
 "options": {"A": "乳清酸核苷酸(OMP)", "B": "尿嘧啶核苷酸(UMP)", "C": "二氢乳清酸", "D": "氨基甲酰天冬氨酸"},
 "answer": "A",
 "explanation": "乳清酸在乳清酸磷酸核糖转移酶催化下与PRPP结合生成乳清酸核苷酸(OMP),OMP再经乳清酸核苷酸脱羧酶脱羧生成UMP;后两步酶融合为UMP合成酶。",
 "difficulty": 2,
 "tags": ["OMP", "乳清酸", "PRPP"]
},
{
 "id": 73,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "嘧啶核苷酸从头合成途径中首先合成的嘧啶核苷酸是?",
 "options": {"A": "UMP", "B": "CTP", "C": "OMP", "D": "dTMP"},
 "answer": "A",
 "explanation": "嘧啶核苷酸从头合成先合成UMP,其他嘧啶核苷酸(CTP、dTMP等)均由UMP转变而来;OMP是UMP的直接前体而非最终产物。",
 "difficulty": 1,
 "tags": ["UMP", "嘧啶合成", "首先合成"]
},
{
 "id": 74,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "动物细胞中催化氨基甲酰磷酸合成的酶是?",
 "options": {"A": "氨基甲酰磷酸合成酶Ⅱ(CPSII)", "B": "氨基甲酰磷酸合成酶Ⅰ(CPSI)", "C": "天冬氨酸转氨甲酰酶", "D": "二氢乳清酸酶"},
 "answer": "A",
 "explanation": "嘧啶从头合成以CO₂、谷氨酰胺为原料,由氨基甲酰磷酸合成酶Ⅱ(CPSII)催化生成氨基甲酰磷酸;CPSII是动物细胞嘧啶核苷酸合成的控制点,受UDP和UTP反馈抑制。",
 "difficulty": 2,
 "tags": ["CPSII", "氨基甲酰磷酸", "嘧啶合成"]
},
{
 "id": 75,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "动物中尿嘧啶核苷酸合成途径前三个酶(氨甲酰磷酸合成酶、天冬氨酸转氨甲酰酶和二氢乳清酸酶)组成的多功能酶是?",
 "options": {"A": "CAD", "B": "UMP合成酶", "C": "ATCase", "D": "嘌呤多酶复合物"},
 "answer": "A",
 "explanation": "动物中嘧啶从头合成前三个酶组成多功能酶CAD,由三条相同的多肽链亚基组成,每一亚基包含全部三个反应的活性中心;最后两步反应的酶融合为UMP合成酶。",
 "difficulty": 2,
 "tags": ["CAD", "多功能酶", "嘧啶合成"]
},
{
 "id": 76,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "truefalse",
 "question": "UMP合成酶(乳清酸磷酸核糖转移酶和乳清酸核苷酸脱羧酶的融合酶)缺陷时,患者患乳清酸尿症。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "A",
 "explanation": "乳清酸尿症是由于乳清酸磷酸核糖转移酶和乳清酸核苷酸脱羧酶(合称UMP合成酶)有缺陷,乳清酸不能转变为UMP,大量乳清酸出现在血液和尿液中,并影响嘧啶核苷酸合成。",
 "difficulty": 2,
 "tags": ["UMP合成酶", "乳清酸尿症", "缺陷"]
},
{
 "id": 77,
 "topic": "嘧啶核苷酸的从头合成",
 "type": "choice",
 "question": "关于乳清酸尿症,下列说法正确的是?",
 "options": {"A": "因乳清酸磷酸核糖转移酶和乳清酸核苷酸脱羧酶缺陷,乳清酸大量出现在血液和尿液中", "B": "因HGPRT缺陷导致尿酸堆积", "C": "因黄嘌呤氧化酶缺陷导致黄嘌呤堆积", "D": "因二氢乳清酸脱氢酶缺陷导致二氢乳清酸堆积"},
 "answer": "A",
 "explanation": "乳清酸尿症是嘧啶合成途径的酶缺陷病:乳清酸磷酸核糖转移酶和乳清酸核苷酸脱羧酶缺陷使乳清酸不能转变为UMP,导致乳清酸大量出现在血液和尿液中,同时嘧啶核苷酸合成受阻。",
 "difficulty": 2,
 "tags": ["乳清酸尿症", "UMP合成酶", "病因"]
},
{
 "id": 78,
 "topic": "UTP向CTP的转变",
 "type": "choice",
 "question": "下列关于UTP转变为CTP的说法,正确的是?",
 "options": {"A": "转变必须发生在尿嘧啶核苷三磷酸水平,只有UTP可以转变为CTP", "B": "尿嘧啶、尿苷均可直接转变为胞嘧啶化合物", "C": "UMP可直接氨基化生成CMP", "D": "UDP与谷氨酰胺反应可直接生成CDP"},
 "answer": "A",
 "explanation": "尿嘧啶、尿嘧啶核苷、尿嘧啶单磷酸和二磷酸核苷酸均不能转变为相应的胞嘧啶化合物,转变必须发生在三磷酸水平,只有UTP在谷氨酰胺提供氨基的条件下可转变为CTP(需ATP)。",
 "difficulty": 3,
 "tags": ["UTP", "CTP", "三磷酸水平"]
},
{
 "id": 79,
 "topic": "UTP向CTP的转变",
 "type": "truefalse",
 "question": "尿嘧啶核苷酸(UMP)可以直接氨基化转变为胞嘧啶核苷酸(CMP)。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "B",
 "explanation": "尿嘧啶、尿嘧啶核苷、尿嘧啶单磷酸和二磷酸核苷酸均不能转变为相应的胞嘧啶化合物,转变必须发生在尿嘧啶核苷三磷酸水平,只有UTP可转变为CTP。",
 "difficulty": 2,
 "tags": ["UMP", "CMP", "三磷酸水平"]
},
{
 "id": 80,
 "topic": "嘧啶核苷酸的补救合成",
 "type": "choice",
 "question": "关于嘧啶核苷酸的补救合成,正确的是?",
 "options": {"A": "胞嘧啶不能直接与PRPP反应,只能通过激酶途径形成胞嘧啶核苷酸", "B": "胞嘧啶可直接与PRPP反应生成CMP", "C": "尿嘧啶不能与1-磷酸核糖反应生成尿苷", "D": "嘧啶核苷酸没有补救合成途径"},
 "answer": "A",
 "explanation": "嘧啶补救合成中,嘌呤(U、T)可与PRPP经嘌呤磷酸核糖转移酶生成嘌呤核苷酸;胞嘧啶不能直接和PRPP反应,只能经尿苷激酶途径(尿苷/胞苷+ATP→UMP/CMP)形成胞嘧啶核苷酸。",
 "difficulty": 3,
 "tags": ["胞嘧啶", "补救合成", "激酶途径"]
},
{
 "id": 81,
 "topic": "嘌呤核苷酸合成的调节",
 "type": "choice",
 "question": "嘌呤核苷酸从头合成途径的第一个控制点(限速反应)是?",
 "options": {"A": "氨基转移到PRPP上形成5-磷酸核糖胺", "B": "IMP氧化生成XMP", "C": "腺苷酸琥珀酸的裂解", "D": "乳清酸与PRPP结合"},
 "answer": "A",
 "explanation": "嘌呤从头合成的第一个控制点在第一步反应:氨基被转移到PRPP上形成5-磷酸核糖胺,催化该反应的酰胺转移酶是变构酶,可被终产物IMP、AMP和GMP抑制。",
 "difficulty": 2,
 "tags": ["嘌呤调节", "酰胺转移酶", "第一个控制点"]
},
{
 "id": 82,
 "topic": "嘌呤核苷酸合成的调节",
 "type": "choice",
 "question": "嘌呤核苷酸合成的调节中,磷酸核糖焦磷酸激酶受哪种物质的反馈抑制?",
 "options": {"A": "IMP、ADP和GDP", "B": "AMP、GMP和CTP", "C": "UDP和UTP", "D": "dATP和dGTP"},
 "answer": "A",
 "explanation": "PRPP是最初底物,其合成酶磷酸核糖焦磷酸激酶受产物IMP、ADP和GDP的反馈抑制(杨荣武版本为IMP、AMP和GMP);PRPP可正调节嘌呤合成。",
 "difficulty": 3,
 "tags": ["磷酸核糖焦磷酸激酶", "反馈抑制", "IMP"]
},
{
 "id": 83,
 "topic": "嘌呤核苷酸合成的调节",
 "type": "truefalse",
 "question": "GMP过量时,其变构效应仅抑制GMP自身的形成,而不影响AMP的形成。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "A",
 "explanation": "嘌呤合成的另两个控制点位于IMP后分支途径的第一步:GMP过量仅抑制其自身形成而不影响AMP形成;反之AMP积累仅抑制自身形成而不影响GMP合成。",
 "difficulty": 2,
 "tags": ["GMP", "AMP", "变构调节"]
},
{
 "id": 84,
 "topic": "嘌呤核苷酸合成的调节",
 "type": "multi",
 "question": "嘌呤核苷酸从头合成途径的三个主要控制点及其酶包括?",
 "options": {"A": "酰胺转移酶(PRPP→5-磷酸核糖胺),被IMP、AMP和GMP抑制", "B": "磷酸核糖焦磷酸激酶,被IMP、ADP和GDP反馈抑制", "C": "IMP后分支途径的第一步(腺苷酸琥珀酸合成酶等),终产物分别抑制自身合成", "D": "黄嘌呤氧化酶,被尿酸抑制"},
 "answer": "ABC",
 "explanation": "嘌呤合成调节的主要控制点:①PRPP→5-磷酸核糖胺(酰胺转移酶,被IMP、AMP、GMP抑制);②PRPP合成酶(磷酸核糖焦磷酸激酶,被IMP、ADP、GDP抑制);③IMP后分支途径第一步(GMP过量抑制GMP形成、AMP过量抑制AMP形成)。黄嘌呤氧化酶属分解代谢酶,不参与合成调节。",
 "difficulty": 3,
 "tags": ["嘌呤调节", "控制点", "反馈抑制"]
},
{
 "id": 85,
 "topic": "嘧啶核苷酸合成的调节",
 "type": "choice",
 "question": "大肠杆菌中嘧啶核苷酸合成的主要调节方式是?",
 "options": {"A": "天冬氨酸转氨甲酰酶(ATCase)受终产物CTP的变构抑制", "B": "CPSII受UDP和UTP的反馈抑制", "C": "二氢乳清酸脱氢酶受NADH抑制", "D": "UMP合成酶受乳清酸抑制"},
 "answer": "A",
 "explanation": "细菌的嘧啶合成主要通过对ATCase活性的控制进行:大肠杆菌的效应物是终产物CTP,CTP结合调节亚基使催化亚基由活性构象转变为无活性构象;ATP可阻止CTP诱导的构象变化。动物细胞则以CPSII为控制点。",
 "difficulty": 3,
 "tags": ["ATCase", "CTP", "细菌调节"]
},
{
 "id": 86,
 "topic": "嘧啶核苷酸合成的调节",
 "type": "choice",
 "question": "动物细胞中嘧啶核苷酸生物合成的控制点是?",
 "options": {"A": "氨基甲酰磷酸合成酶Ⅱ(CPSII),受UDP和UTP反馈抑制", "B": "天冬氨酸转氨甲酰酶,受CTP抑制", "C": "二氢乳清酸酶,受UMP抑制", "D": "乳清酸核苷酸脱羧酶,受OMP抑制"},
 "answer": "A",
 "explanation": "在动物细胞中ATCase不是调节酶,嘌呤核苷酸生物合成的控制点是氨基甲酰磷酸合成酶Ⅱ(CPSII),它受UDP和UTP的反馈抑制——这是细菌与动物嘧啶合成调节的重要区别。",
 "difficulty": 3,
 "tags": ["CPSII", "UDP", "UTP", "动物调节"]
},
{
 "id": 87,
 "topic": "嘌呤与嘧啶核苷酸从头合成的异同",
 "type": "choice",
 "question": "嘌呤与嘧啶核苷酸从头合成的共同原料是?",
 "options": {"A": "5-磷酸核糖(活化为PRPP)、CO₂、谷氨酰胺、天冬氨酸", "B": "5-磷酸核糖、甘氨酸、谷氨酰胺、天冬氨酸", "C": "PRPP、甘氨酸、甲酸盐、CO₂", "D": "核糖-1-磷酸、谷氨酰胺、CO₂、天冬氨酸"},
 "answer": "A",
 "explanation": "嘌呤与嘧啶从头合成共同底物为5-磷酸核糖(需活化为PRPP)、CO₂、Gln、Asp;区别在于甘氨酸和一碳单位只参与嘌呤环合成,不参与嘧啶环。",
 "difficulty": 2,
 "tags": ["共同原料", "PRPP", "CO2"]
},
{
 "id": 88,
 "topic": "嘌呤与嘧啶核苷酸从头合成的异同",
 "type": "choice",
 "question": "嘌呤核苷酸从头合成中,被GMP抑制的关键酶是?",
 "options": {"A": "次黄嘌呤核苷酸脱氢酶", "B": "腺苷酸琥珀酸合成酶", "C": "5-磷酸核糖焦磷酸激酶", "D": "Gln磷酸核糖焦磷酸酰胺转移酶"},
 "answer": "A",
 "explanation": "嘌呤合成关键酶:①5-磷酸核糖焦磷酸激酶(被IMP、ADP、GDP抑制);②Gln磷酸核糖焦磷酸酰胺转移酶(被IMP、AMP、GMP抑制);③腺苷酸琥珀酸合成酶(被AMP抑制);④次黄嘌呤核苷酸脱氢酶(被GMP抑制)。【OCR残缺,④已按教材补全】",
 "difficulty": 3,
 "tags": ["关键酶", "GMP", "次黄嘌呤核苷酸脱氢酶"]
},
{
 "id": 89,
 "topic": "嘌呤与嘧啶核苷酸从头合成的异同",
 "type": "multi",
 "question": "关于嘌呤与嘧啶核苷酸从头合成比较,正确的有?",
 "options": {"A": "嘌呤在PRPP基础上合成嘌呤环,直接形成核苷酸,最先合成IMP", "B": "嘧啶先合成嘧啶环,再与PRPP结合,最先合成UMP", "C": "两者对高等动物来说主要在肝脏的细胞溶胶中进行", "D": "嘌呤最先合成的核苷酸是UMP,嘧啶最先合成IMP"},
 "answer": "ABC",
 "explanation": "嘌呤合成:在PRPP基础上合成嘌呤环、不出现游离嘌呤,最先合成IMP,再完成AMP和GMP;嘧啶合成:先合成嘧啶环再与PRPP结合,最先合成UMP;两者合成部位均为肝脏细胞溶胶,都含从头与补救两种途径;D把两者产物颠倒了。",
 "difficulty": 2,
 "tags": ["嘌呤", "嘧啶", "从头合成比较"]
},
{
 "id": 90,
 "topic": "嘌呤与嘧啶核苷酸从头合成的异同",
 "type": "short",
 "question": "比较嘌呤核苷酸与嘧啶核苷酸从头合成的异同点。",
 "answer": "①相同点:合成原料基本相同(共同底物为5-磷酸核糖/PRPP、CO₂、Gln、Asp);合成部位对高等动物来说主要在肝脏的细胞溶胶;都有从头合成和补救合成两种途径;都先合成一个有关的核苷酸,再进一步合成其他核苷酸;②不同点:嘌呤在PRPP基础上逐步合成嘌呤环,不出现游离嘌呤,最先合成IMP,再在IMP基础上完成AMP和GMP的合成;嘧啶先合成嘧啶环再与PRPP结合,最先合成UMP,以UMP为基础完成CTP、dTMP的合成;关键酶不同(嘌呤:磷酸核糖焦磷酸激酶、酰胺转移酶、腺苷酸琥珀酸合成酶、次黄嘌呤核苷酸脱氢酶;嘧啶:ATCase/CPSII)。",
 "explanation": "嘌呤与嘧啶从头合成的异同是本章核心简答考点(★★),需从原料、部位、途径、产物顺序、关键酶五个维度作答。",
 "difficulty": 3,
 "tags": ["嘌呤", "嘧啶", "从头合成", "异同"]
},
]
