# -*- coding: utf-8 -*-
# 第二十七章 batch4: 题 91-115 (NMP→NDP→NTP / 脱氧核糖核苷酸合成 / dTMP / 辅酶核苷酸 / 抗代谢物)
QUESTIONS = [
{
 "id": 91,
 "topic": "核苷单磷酸向核苷三磷酸的转变",
 "type": "choice",
 "question": "核苷单磷酸激酶催化的反应特点是?",
 "options": {"A": "特异性只针对碱基,ATP常作为磷酸基团的供体", "B": "特异性针对核糖,对碱基无要求", "C": "没有特异性,可催化任何核苷酸", "D": "只能催化AMP的磷酸化"},
 "answer": "A",
 "explanation": "核苷单磷酸激酶的特异性只针对碱基,如腺苷酸激酶催化AMP+ATP→2ADP、鸟苷酸激酶催化GMP+ATP→GDP+ADP;由于ATP含量很高,常作为磷酸基团供体。",
 "difficulty": 2,
 "tags": ["核苷单磷酸激酶", "特异性", "ATP供体"]
},
{
 "id": 92,
 "topic": "核苷单磷酸向核苷三磷酸的转变",
 "type": "choice",
 "question": "腺苷酸激酶催化的反应是?",
 "options": {"A": "AMP+ATP→2ADP", "B": "GMP+ATP→GDP+ADP", "C": "ADP+Pi→ATP", "D": "AMP+UTP→ADP+UDP"},
 "answer": "A",
 "explanation": "腺苷酸激酶催化AMP+ATP→2ADP;鸟苷酸激酶催化GMP+ATP→GDP+ADP,二者均以ATP为磷酸基团供体。",
 "difficulty": 2,
 "tags": ["腺苷酸激酶", "AMP", "ADP"]
},
{
 "id": 93,
 "topic": "核苷单磷酸向核苷三磷酸的转变",
 "type": "choice",
 "question": "催化NTP与NDP之间相互转变、没有底物特异性的酶是?",
 "options": {"A": "核苷二磷酸激酶", "B": "核苷单磷酸激酶", "C": "核苷酸还原酶", "D": "核苷三磷酸酶"},
 "answer": "A",
 "explanation": "核苷二磷酸激酶没有特异性,催化NTP+N₁DP→N₁TP+NDP的可逆反应;ATP的合成途径很多,GTP可部分由TCA循环合成,其余部分和其他NTP由核苷二磷酸激酶催化形成,磷酸基团由ATP提供。",
 "difficulty": 2,
 "tags": ["核苷二磷酸激酶", "无特异性", "NTP"]
},
{
 "id": 94,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "choice",
 "question": "生物体内脱氧核糖核苷酸的主要合成方式是?",
 "options": {"A": "由核糖核苷酸经核糖核苷酸还原酶还原生成", "B": "由碱基与脱氧核糖-1-磷酸直接合成", "C": "由胸腺嘧啶从头合成", "D": "由脱氧核苷激酶单独完成"},
 "answer": "A",
 "explanation": "生物体内脱氧核糖核苷酸主要由相应的核糖核苷酸还原生成:腺嘌呤、鸟嘌呤、胞嘧啶和尿嘧啶核糖核苷酸经还原,脱去核糖第二位碳原子上的氧,即成为相应的脱氧核糖核苷酸;催化酶是核糖核苷酸还原酶。",
 "difficulty": 2,
 "tags": ["脱氧核糖核苷酸", "核糖核苷酸还原酶", "还原"]
},
{
 "id": 95,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "choice",
 "question": "核糖核苷酸还原酶的底物是?",
 "options": {"A": "4种NDP(ADP、GDP、UDP和CDP)", "B": "4种NTP", "C": "4种NMP", "D": "dNDP"},
 "answer": "A",
 "explanation": "通常核糖核苷酸是在核糖二磷酸(NDP)水平被还原的,4种NDP即ADP、GDP、UDP和CDP是还原反应的底物(★考点);胸腺嘧啶脱氧核苷酸则由dUMP甲基化生成。",
 "difficulty": 2,
 "tags": ["NDP", "底物", "核糖核苷酸还原酶"]
},
{
 "id": 96,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "multi",
 "question": "关于核糖核苷酸还原酶的结构,正确的有?",
 "options": {"A": "R1含2条相同多肽链,每条有2个调节位点(酶活性调节位点和底物特异调节位点)和一对巯基", "B": "R2含2条多肽链,各有1个酪氨酸基和1个双核铁(Fe³⁺)辅因子", "C": "酶的活性部位位于R1与R2亚基的界面处", "D": "R1和R2亚基分开时即具有催化活性"},
 "answer": "ABC",
 "explanation": "核糖核苷酸还原酶含R1和R2两个亚基:R1有2个调节位点和一对参与还原反应的巯基;R2各有1个酪氨酸基和1个双核铁(Fe³⁺)辅因子;活性部位在R1/R2界面,R1和R2只有结合在一起并存在Mg²⁺时才有催化活性,分开无活性。",
 "difficulty": 3,
 "tags": ["核糖核苷酸还原酶", "R1R2", "结构"]
},
{
 "id": 97,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "truefalse",
 "question": "核糖核苷酸还原酶的R1和R2亚基分开时即有催化活性。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "B",
 "explanation": "核糖核苷酸还原酶的活性部位在R1与R2亚基的界面处,R1和R2只有结合在一起、并有Mg²⁺存在时才有催化活性,分开时无活性。",
 "difficulty": 2,
 "tags": ["核糖核苷酸还原酶", "R1R2", "Mg2+"]
},
{
 "id": 98,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "choice",
 "question": "核糖核苷酸还原为脱氧核糖核苷酸所需氢的最终给体是?",
 "options": {"A": "NADPH", "B": "NADH", "C": "FADH₂", "D": "谷胱甘肽"},
 "answer": "A",
 "explanation": "核糖核苷酸被还原为脱氧核糖核苷酸需提供两个氢原子,酶失去两个氢后需氢供体使其恢复,氢的最终给体是NADPH,其间经氢携带蛋白(硫氧还蛋白/谷氧还蛋白)再转移给还原酶。",
 "difficulty": 2,
 "tags": ["NADPH", "氢供体", "脱氧核糖核苷酸"]
},
{
 "id": 99,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "choice",
 "question": "硫氧还蛋白在脱氧核糖核苷酸合成中的作用是?",
 "options": {"A": "作为氢携带蛋白,含一对巯基,给出两个氢后变为二硫化物型,再由硫氧还蛋白还原酶(含FAD)经NADPH还原", "B": "直接提供磷酸基团", "C": "催化核糖核苷酸还原酶的构象变化", "D": "作为底物被还原成dNDP"},
 "answer": "A",
 "explanation": "硫氧还蛋白是广泛参与氧化还原反应的小分子蛋白质,含一对巯基,给出两个氢后变为氧化型(二硫化物型),在硫氧还蛋白还原酶(含FAD的黄素酶)催化下被NADPH还原,从而循环传递氢。",
 "difficulty": 2,
 "tags": ["硫氧还蛋白", "氢携带蛋白", "NADPH"]
},
{
 "id": 100,
 "topic": "脱氧核糖核苷酸的合成",
 "type": "choice",
 "question": "谷氧还蛋白还原后再生所需的还原剂是?",
 "options": {"A": "两分子还原型谷胱甘肽(GSH)", "B": "NADH", "C": "FADH₂", "D": "硫辛酸"},
 "answer": "A",
 "explanation": "谷氧还蛋白也能起传递氢的作用:谷氧还蛋白还原酶结合两分子的谷胱甘肽(GSH,氧化型为GSSG)可以还原谷氧还蛋白;谷胱甘肽还原酶也是一种黄素酶,从NADPH获得氢并还原谷胱甘肽。",
 "difficulty": 3,
 "tags": ["谷氧还蛋白", "谷胱甘肽", "GSH"]
},
{
 "id": 101,
 "topic": "核糖核苷酸还原酶的调节",
 "type": "choice",
 "question": "核糖核苷酸还原酶的活性调节中,正效应物和负效应物分别是?",
 "options": {"A": "ATP是正效应物(激活),dATP是负效应物(抑制)", "B": "dATP是正效应物,ATP是负效应物", "C": "dGTP是正效应物,dTTP是负效应物", "D": "CTP是正效应物,UTP是负效应物"},
 "answer": "A",
 "explanation": "当ATP结合于酶活性调节位点时酶被激活,ATP是正效应物;dATP结合时酶被抑制,是负效应物(dATP存在时酶从聚合变为环状);dATP的浓度反映四种dNTP水平,ATP反映核糖核苷酸和供能水平。",
 "difficulty": 2,
 "tags": ["核糖核苷酸还原酶", "ATP", "dATP"]
},
{
 "id": 102,
 "topic": "核糖核苷酸还原酶的调节",
 "type": "choice",
 "question": "dTTP结合核糖核苷酸还原酶的底物特异性调节位点后,其效应是?",
 "options": {"A": "促进GDP还原,抑制UDP和CDP还原", "B": "促进UDP和CDP还原,抑制GDP还原", "C": "促进ADP还原,抑制其他底物还原", "D": "同时抑制所有底物的还原"},
 "answer": "A",
 "explanation": "底物特异性调节位点可被ATP、dATP、dGTP和dTTP结合:dTTP结合促进GDP还原,但抑制UDP和CDP还原;dGTP结合促进ADP还原,抑制UDP、CDP和GDP还原;ATP或dATP结合则优先还原嘌呤核苷酸底物(UDP或CDP)。",
 "difficulty": 3,
 "tags": ["dTTP", "GDP还原", "底物特异调节"]
},
{
 "id": 103,
 "topic": "核糖核苷酸还原酶的调节",
 "type": "multi",
 "question": "关于四种脱氧核糖核苷二磷酸之间平衡关系的调节,正确的有?",
 "options": {"A": "ATP或dATP结合调节位点时,还原酶优先还原UDP或CDP", "B": "dTTP结合促进GDP还原,抑制UDP和CDP还原", "C": "dGTP结合促进ADP还原,抑制UDP、CDP和GDP还原", "D": "dATP浓度可作为反映四种dNTP水平的指标"},
 "answer": "ABCD",
 "explanation": "核糖核苷酸还原酶通过底物特异性调节位点(可被ATP、dATP、dGTP、dTTP结合)协调四种dNDP的平衡:dATP浓度反映四种dNTP水平;ATP或dATP结合优先还原嘌呤核苷酸底物(UDP/CDP);dTTP促进GDP还原;dGTP促进ADP还原。",
 "difficulty": 3,
 "tags": ["核糖核苷酸还原酶", "dNTP平衡", "调节"]
},
{
 "id": 104,
 "topic": "胸腺嘧啶核苷酸的形成",
 "type": "choice",
 "question": "胸腺嘧啶核苷酸(dTMP)的直接前体是?",
 "options": {"A": "尿嘧啶脱氧核糖核苷酸(dUMP)", "B": "胞嘧啶脱氧核糖核苷酸(dCMP)", "C": "尿嘧啶核苷酸(UMP)", "D": "胸腺嘧啶碱基"},
 "answer": "A",
 "explanation": "dTMP由dUMP经甲基化生成:催化酶为胸腺嘧啶核苷酸合酶,甲基供体是N₅,N₁₀-亚甲基四氢叶酸;dUMP则来自UDP还原或dCTP脱氨两条途径。",
 "difficulty": 2,
 "tags": ["dTMP", "dUMP", "甲基化"]
},
{
 "id": 105,
 "topic": "胸腺嘧啶核苷酸的形成",
 "type": "choice",
 "question": "dUMP甲基化生成dTMP的甲基供体是?",
 "options": {"A": "N₅,N₁₀-亚甲基四氢叶酸", "B": "S-腺苷甲硫氨酸", "C": "甲酸盐", "D": "N₁₀-甲酰四氢叶酸"},
 "answer": "A",
 "explanation": "催化dUMP甲基化的酶是胸腺嘧啶核苷酸合酶,甲基供体为N₅,N₁₀-亚甲基四氢叶酸,它给出亚甲基并使其还原成甲基,自身变为二氢叶酸(这正是甲氨蝶呤等叶酸类似物抑制dTMP合成的基础)。",
 "difficulty": 3,
 "tags": ["dTMP", "甲基供体", "亚甲基四氢叶酸"]
},
{
 "id": 106,
 "topic": "胸腺嘧啶核苷酸的形成",
 "type": "choice",
 "question": "氨基蝶呤、氨甲蝶呤抑制dTMP合成的机制是?",
 "options": {"A": "作为叶酸的结构类似物与二氢叶酸还原酶牢固结合,阻止四氢叶酸生成,抑制一碳单位转移反应", "B": "直接抑制胸腺嘧啶核苷酸合酶", "C": "与dUMP竞争胸腺嘧啶核苷酸合酶的底物位点", "D": "抑制核糖核苷酸还原酶"},
 "answer": "A",
 "explanation": "氨基蝶呤、氨甲蝶呤是叶酸的结构类似物,能与二氢叶酸还原酶牢固结合,阻止四氢叶酸的再生,从而抑制四氢叶酸参与的各种一碳单位转移反应,最终抑制dTMP合成,影响DNA合成,故为抗肿瘤药物。",
 "difficulty": 3,
 "tags": ["氨甲蝶呤", "二氢叶酸还原酶", "一碳单位"]
},
{
 "id": 107,
 "topic": "胸腺嘧啶核苷酸的形成",
 "type": "multi",
 "question": "尿嘧啶脱氧核苷酸(dUMP)的来源途径包括?",
 "options": {"A": "UDP还原为dUDP,经磷酸化生成dUTP,再由dUTP酶去磷酸化生成dUMP", "B": "dCTP脱氨生成dUTP,再转变成dUMP", "C": "UMP直接还原生成dUMP", "D": "胸腺嘧啶与脱氧核糖-1-磷酸直接合成"},
 "answer": "AB",
 "explanation": "dUMP两条合成途径:①UDP→dUDP→(磷酸化)→dUTP→(dUTP酶直接从三磷酸水平去磷酸化)→dUMP;②dCTP脱氨→dUTP→dUMP。C错在还原发生在二磷酸水平而非单磷酸;D是脱氧核苷的合成方式。",
 "difficulty": 3,
 "tags": ["dUMP", "dUTP", "来源途径"]
},
{
 "id": 108,
 "topic": "辅酶核苷酸的生物合成",
 "type": "choice",
 "question": "下列辅酶中不含嘌呤核苷酸的是?",
 "options": {"A": "FMN", "B": "FAD", "C": "NAD⁺", "D": "CoA"},
 "answer": "A",
 "explanation": "体内NAD⁺、NADP⁺、FMN、FAD、CoASH等辅酶均为核苷酸衍生物,除FMN不含嘌呤碱外,其余都含嘌呤核苷酸(FMN仅含核黄素与磷酸,无腺嘌呤)。",
 "difficulty": 2,
 "tags": ["FMN", "核苷酸衍生物", "嘌呤碱"]
},
{
 "id": 109,
 "topic": "辅酶核苷酸的生物合成",
 "type": "truefalse",
 "question": "NAD⁺、NADP⁺、FMN、FAD和CoASH都是核苷酸衍生物,且都含有嘌呤核苷酸。",
 "options": {"A": "正确", "B": "错误"},
 "answer": "B",
 "explanation": "这些辅酶均为核苷酸衍生物,但FMN不含嘌呤碱(仅含核黄素-5'-磷酸),其余NAD⁺、NADP⁺、FAD、CoASH都含嘌呤核苷酸(腺嘌呤)。",
 "difficulty": 2,
 "tags": ["辅酶", "FMN", "核苷酸衍生物"]
},
{
 "id": 110,
 "topic": "核苷酸的抗代谢物",
 "type": "choice",
 "question": "抗代谢物的定义是?",
 "options": {"A": "化学结构与必需代谢物相似、能竞争性拮抗其正常代谢作用的物质", "B": "对微生物有毒的代谢产物", "C": "抑制所有酶活性的化合物", "D": "结构类似物中无药用价值的一类物质"},
 "answer": "A",
 "explanation": "抗代谢物是指在化学结构上与必需代谢物结构相似、具有竞争性拮抗其正常代谢作用的物质;抗代谢物的研究对阐明药物作用机制、寻找与设计新药有重要指导作用。",
 "difficulty": 1,
 "tags": ["抗代谢物", "定义", "竞争性拮抗"]
},
{
 "id": 111,
 "topic": "核苷酸的抗代谢物",
 "type": "choice",
 "question": "6-巯基嘌呤(6-MP)属于哪一类抗代谢物,其作用机制是?",
 "options": {"A": "次黄嘌呤抗代谢物;体内生成6-MP核苷酸,抑制IMP转变为AMP及GMP的反应,并反馈抑制嘌呤合成调节酶", "B": "叶酸类似物;抑制二氢叶酸还原酶", "C": "谷氨酰胺类似物;干扰Gln参与嘌呤合成", "D": "核苷类似物;抑制核苷酸还原酶"},
 "answer": "A",
 "explanation": "6-MP结构与次黄嘌呤相似,可在体内经磷酸核糖化生成6-MP核苷酸,抑制IMP转变为AMP及GMP的反应,还反馈抑制嘌呤合成的调节酶,并降低脱氧核苷酸合成,起抗癌作用。",
 "difficulty": 2,
 "tags": ["6-巯基嘌呤", "次黄嘌呤类似物", "IMP"]
},
{
 "id": 112,
 "topic": "核苷酸的抗代谢物",
 "type": "choice",
 "question": "5-氟尿嘧啶(5-FU)的抗癌作用机制是?",
 "options": {"A": "体内合成FdUMP类似dUMP,竞争性抑制dTMP合成酶(自杀性作用物);还可合成FUTP掺入RNA破坏其结构与功能", "B": "抑制二氢叶酸还原酶", "C": "抑制核糖核苷酸还原酶", "D": "反馈抑制PRPP酰胺转移酶"},
 "answer": "A",
 "explanation": "5-FU在体内合成FdUMP,与dUMP结构类似,竞争性抑制dTMP合成酶(自杀性作用物),阻断dTMP合成;5-FU还可合成FUTP,在RNA合成时以FUMP形式掺入,破坏RNA的结构和功能。",
 "difficulty": 2,
 "tags": ["5-氟尿嘧啶", "FdUMP", "dTMP合成酶"]
},
{
 "id": 113,
 "topic": "核苷酸的抗代谢物",
 "type": "choice",
 "question": "氮杂丝氨酸抑制嘌呤核苷酸合成的机制是?",
 "options": {"A": "作为谷氨酰胺类似物,干扰Gln在嘌呤核苷酸合成中的作用", "B": "作为天冬氨酸类似物抑制腺苷酸琥珀酸合成酶", "C": "作为叶酸类似物抑制一碳单位转移", "D": "作为次黄嘌呤类似物抑制HGPRT"},
 "answer": "A",
 "explanation": "氮杂丝氨酸是谷氨酰胺的结构类似物,可干扰谷氨酰胺在嘌呤核苷酸合成中的作用(谷氨酰胺为嘌呤环N3、N9提供酰胺基),从而抑制嘌呤核苷酸的合成。",
 "difficulty": 2,
 "tags": ["氮杂丝氨酸", "谷氨酰胺类似物", "嘌呤合成"]
},
{
 "id": 114,
 "topic": "核苷酸的抗代谢物",
 "type": "choice",
 "question": "阿糖胞苷的抗癌机制是?",
 "options": {"A": "抑制核苷酸还原酶,阻止核苷酸转变为脱氧核苷酸(如抑制CDP还原成dCDP)", "B": "抑制胸腺嘧啶核苷酸合酶", "C": "抑制二氢叶酸还原酶", "D": "抑制DNA聚合酶以外的核酸酶"},
 "answer": "A",
 "explanation": "阿糖胞苷是核苷类似物,能抑制核苷酸还原酶,阻止核苷酸转变为脱氧核苷酸(典型的是抑制CDP还原成dCDP),从而阻断DNA合成所需的脱氧核苷酸供应。",
 "difficulty": 2,
 "tags": ["阿糖胞苷", "核苷酸还原酶", "CDP"]
},
{
 "id": 115,
 "topic": "核苷酸的抗代谢物",
 "type": "multi",
 "question": "下列抗代谢物与作用机制的对应,正确的有?",
 "options": {"A": "6-巯基嘌呤(次黄嘌呤类似物)——抑制IMP转变为AMP及GMP", "B": "5-氟尿嘧啶——体内生成FdUMP,竞争性抑制dTMP合成酶", "C": "氨甲蝶呤(叶酸类似物)——抑制二氢叶酸还原酶,干扰一碳单位代谢", "D": "阿糖胞苷——抑制核苷酸还原酶,阻止NDP还原为dNDP"},
 "answer": "ABCD",
 "explanation": "常见抗代谢物及其机制:6-MP(次黄嘌呤类似物)抑制IMP→AMP/GMP并反馈抑制嘌呤合成调节酶;5-FU生成FdUMP抑制dTMP合成酶;氨基蝶呤/氨甲蝶呤(叶酸类似物)抑制二氢叶酸还原酶;氮杂丝氨酸(Gln类似物)干扰嘌呤合成;阿糖胞苷(核苷类似物)抑制核苷酸还原酶。",
 "difficulty": 3,
 "tags": ["抗代谢物", "作用机制", "配对"]
},
]
