# -*- coding: utf-8 -*-
# 第三十六章 第二批:choice 28-45 + truefalse 46-59

Q = [
{"type":"choice","topic":"基因敲低(RNA干扰)","question":"RNA 干扰(RNAi)引起基因沉默的机制是?",
"options":{"A":"小 RNA 分子与启动子结合抑制转录起始","B":"引入细胞中的短 RNA 分子引导降解特定已被转录的 mRNA 分子","C":"将基因组中的基因彻底删除","D":"使组蛋白发生不可逆修饰"},
"answer":"B","explanation":"RNA 干扰通过在细胞中引入短 RNA 分子(siRNA 等),降解特定的已被转录的 mRNA 分子,从而在 RNA 水平使基因表达下调。","difficulty":2,"tags":["RNAi","基因敲低","mRNA降解"],"topic":"基因敲低(RNA干扰)"},
{"type":"choice","topic":"基因敲低(RNA干扰)","question":"RNA 干扰中,引导特异性降解目标 mRNA 的小 RNA 分子是?",
"options":{"A":"rRNA","B":"tRNA","C":"siRNA(小干扰 RNA)","D":"snRNA"},
"answer":"C","explanation":"RNA 干扰依赖 siRNA 等小 RNA 分子,借助 RNA 诱导沉默复合体(RISC)特异性地识别并降解目标 mRNA,使对应基因表达下调。","difficulty":2,"tags":["RNAi","siRNA"],"topic":"基因敲低(RNA干扰)"},
{"type":"choice","topic":"基因敲除与敲低比较","question":"与基因敲除相比,基因敲低的特点在于?",
"options":{"A":"彻底消除细胞内目标蛋白质的产生","B":"作用于基因组 DNA 层面","C":"不会像敲除那样彻底消除目标蛋白质的产生,属于部分降低","D":"只能用于体外培养细胞"},
"answer":"C","explanation":"基因敲低通过 RNA 干扰降解 mRNA,基因并未从基因组中消失,因此目标蛋白质的产生只是被显著降低而不会彻底消除;基因敲除则在 DNA 水平彻底删除基因。","difficulty":2,"tags":["基因敲除","基因敲低","比较"],"topic":"基因敲除与敲低比较"},
{"type":"choice","topic":"基因敲除与敲低比较","question":"下列关于基因敲除与基因敲低的比较,错误的是?",
"options":{"A":"基因敲除在 DNA 水平彻底删除目标基因","B":"基因敲低通过 RNA 干扰在 RNA 水平降解 mRNA","C":"基因敲低比基因敲除对基因功能的抑制更彻底","D":"两者都可用于研究基因功能"},
"answer":"C","explanation":"基因敲除彻底删除基因,功能完全丧失;基因敲低仅降解 mRNA,蛋白产量降低而不彻底,因此敲除对基因功能的抑制更彻底。","difficulty":2,"tags":["基因敲除","基因敲低","比较"],"topic":"基因敲除与敲低比较"},
{"type":"choice","topic":"比较基因组学","question":"比较基因组学的主要研究内容是?",
"options":{"A":"比较不同物种基因组的结构、序列与功能,揭示物种间的进化关系与功能保守性","B":"比较不同蛋白质的分子量","C":"比较不同细胞的代谢速率","D":"比较不同基因的表达量"},
"answer":"A","explanation":"比较基因组学通过比较不同物种基因组序列与结构,鉴定保守序列与功能元件,揭示基因的进化规律和物种间的亲缘关系。","difficulty":2,"tags":["比较基因组学","进化"],"topic":"比较基因组学"},
{"type":"choice","topic":"蛋白质组学概述","question":"与基因组相比,蛋白质组的一个重要特点是?",
"options":{"A":"蛋白质组是静态不变的","B":"蛋白质组是动态的,随组织类型、发育阶段、生理和病理状态而变化","C":"蛋白质组与基因组完全一一对应","D":"蛋白质组只存在于原核生物"},
"answer":"B","explanation":"蛋白质组是特定时间和条件下细胞或组织表达的全部蛋白质,受发育阶段、生理状态等影响而动态变化,且同一基因可产生多种蛋白质,故与基因组并非一一对应。","difficulty":2,"tags":["蛋白质组","动态性"],"topic":"蛋白质组学概述"},
{"type":"choice","topic":"二维电泳(2-DE)","question":"二维电泳(2-DE)中,第一维等电聚焦电泳依据什么性质分离蛋白质?",
"options":{"A":"分子量","B":"等电点","C":"疏水性","D":"多肽链长度"},
"answer":"B","explanation":"第一维利用非变性等电聚焦电泳,使保持天然构象的蛋白质根据各自的等电点差异分离;第二维 SDS-PAGE 则按多肽链长度(分子量)分离。","difficulty":1,"tags":["2-DE","等电聚焦","等电点"],"topic":"二维电泳(2-DE)"},
{"type":"choice","topic":"二维电泳(2-DE)","question":"二维电泳第二维 SDS-PAGE 中,SDS 的作用是?",
"options":{"A":"使蛋白质带上均匀的负电荷并变性,使电泳迁移率只取决于多肽链长度(分子量)","B":"使蛋白质带上均匀的正电荷","C":"使蛋白质保持天然构象","D":"使蛋白质形成沉淀"},
"answer":"A","explanation":"SDS 与蛋白质结合使蛋白质变性并带上与质量成正比的大量负电荷,掩盖了蛋白质原有的电荷差异,使迁移率只取决于多肽链长度(分子量)。","difficulty":2,"tags":["2-DE","SDS-PAGE","SDS"],"topic":"二维电泳(2-DE)"},
{"type":"choice","topic":"二维电泳(2-DE)","question":"下列关于二维电泳(2-DE)的叙述,错误的是?",
"options":{"A":"第一维采用非变性等电聚焦电泳","B":"第二维采用 SDS-PAGE","C":"2-DE 可同时将数千种蛋白质按等电点和分子量分开","D":"2-DE 可以直接测定蛋白质的氨基酸序列"},
"answer":"D","explanation":"2-DE 只能按等电点和分子量将蛋白质混合物分离成斑点,不能测定氨基酸序列;序列信息需借助质谱等后续鉴定手段获得。","difficulty":2,"tags":["2-DE","局限性"],"topic":"二维电泳(2-DE)"},
{"type":"choice","topic":"质谱鉴定蛋白质","question":"质谱鉴定蛋白质时,将蛋白质酶解为肽段混合物,通过测定各肽段的精确质量构建的图谱称为?",
"options":{"A":"基因组指纹图谱","B":"肽质量指纹图谱(PMF)","C":"限制性酶切图谱","D":"杂交图谱"},
"answer":"B","explanation":"蛋白质经酶解产生的肽段混合物,其精确质量的组合是蛋白质特有的'指纹',与数据库比对即可鉴定蛋白质,称为肽质量指纹图谱。","difficulty":2,"tags":["质谱","肽质量指纹图谱"],"topic":"质谱鉴定蛋白质"},
{"type":"choice","topic":"质谱鉴定蛋白质","question":"蛋白质组学中常用的软电离质谱技术是?",
"options":{"A":"电子轰击电离质谱","B":"MALDI-TOF(基质辅助激光解吸电离-飞行时间质谱)","C":"化学电离质谱","D":"电感耦合等离子体质谱"},
"answer":"B","explanation":"MALDI-TOF 用基质辅助激光解吸使大分子肽段软电离,再以飞行时间测定质荷比,是蛋白质组学高通量鉴定蛋白质的常用质谱技术。","difficulty":2,"tags":["质谱","MALDI-TOF"],"topic":"质谱鉴定蛋白质"},
{"type":"choice","topic":"质谱鉴定蛋白质","question":"MALDI-TOF 质谱中,'TOF' 是指?",
"options":{"A":"飞行时间","B":"四极杆分析器","C":"离子阱分析器","D":"三重四极杆"},
"answer":"A","explanation":"TOF 即飞行时间(time of flight),不同质荷比的离子在飞行管中飞行时间不同,据此测定其质荷比,实现质量分析。","difficulty":1,"tags":["质谱","TOF"],"topic":"质谱鉴定蛋白质"},
{"type":"choice","topic":"蛋白质相互作用网络","question":"分析蛋白质-蛋白质相互作用网络时,通用的一类分离富集技术是?",
"options":{"A":"亲和层析","B":"凝胶过滤层析","C":"透析","D":"超速离心"},
"answer":"A","explanation":"蛋白质相互作用网络分析中,一般将亲和肽段标签与目标蛋白质融合,利用标签特异的亲和层析分离与每种融合蛋白质相互作用的蛋白质复合体。","difficulty":2,"tags":["蛋白质相互作用","亲和层析"],"topic":"蛋白质相互作用网络"},
{"type":"choice","topic":"蛋白质相互作用网络","question":"将亲和肽段标签与蛋白质融合,再用标签特异性亲和层析逐一分离与其相互作用的蛋白质复合体的策略,称为?",
"options":{"A":"酵母双杂交","B":"标签亲和纯化","C":"免疫沉淀","D":"蛋白质芯片"},
"answer":"B","explanation":"该方法将特定的亲和肽段标签逐一与每种蛋白质融合,通过肽段标签特异的亲和层析逐一分离得到与每一种融合蛋白质相互作用的蛋白质复合体,进而分析相互作用网络。","difficulty":3,"tags":["蛋白质相互作用","标签亲和纯化"],"topic":"蛋白质相互作用网络"},
{"type":"choice","topic":"蛋白质组学研究流程","question":"蛋白质组学研究的典型技术流程是?",
"options":{"A":"测序→拼接→注释","B":"蛋白质分离(如 2-DE)→蛋白质鉴定(如质谱)→生物信息学分析","C":"构建文库→克隆→测序","D":"杂交→扫描→拼接"},
"answer":"B","explanation":"蛋白质组学先以 2-DE 等高效分离技术将蛋白质混合物分离,再用质谱等高通量手段鉴定各蛋白质,最后借助生物信息学进行数据存储、分析与功能阐释。","difficulty":2,"tags":["蛋白质组学","技术流程"],"topic":"蛋白质组学研究流程"},
{"type":"choice","topic":"生物信息学","question":"生物信息学在组学研究中的核心作用是?",
"options":{"A":"直接合成蛋白质","B":"对海量序列与表达数据进行存储、比对、分析和功能预测","C":"纯化蛋白质样品","D":"培养细胞"},
"answer":"B","explanation":"生物信息学运用计算机技术对基因组、转录组、蛋白质组产生的海量数据进行存储、比对、拼接与功能注释,是组学研究不可或缺的支撑。","difficulty":1,"tags":["生物信息学","数据分析"],"topic":"生物信息学"},
{"type":"choice","topic":"其他组学(转录组学等)","question":"转录组学主要研究的是?",
"options":{"A":"特定细胞或组织中全部转录产物(如 mRNA)的种类及表达水平","B":"全部蛋白质的结构与功能","C":"全部小分子代谢物","D":"基因组全部 DNA 序列"},
"answer":"A","explanation":"转录组学在整体水平研究特定细胞或组织全部转录产物(mRNA 等)的种类与表达水平,常借助 DNA 芯片或 RNA 测序实现高通量分析。","difficulty":2,"tags":["转录组学","转录组"],"topic":"其他组学(转录组学等)"},
{"type":"choice","topic":"组学应用(医学)","question":"基因组学与蛋白质组学在医学上的重要应用方向是?",
"options":{"A":"疾病标志物发现、疾病机制研究与个体化诊疗","B":"只能用于模式生物的基础研究","C":"仅用于研究生物进化","D":"只能用于农业育种"},
"answer":"A","explanation":"通过比较疾病与正常状态的基因组、转录组和蛋白质组差异,可以发现疾病标志物与药物靶点,支持疾病诊断和个体化诊疗,是转化医学的重要基础。","difficulty":1,"tags":["组学","医学应用"],"topic":"组学应用(医学)"},
# ---------- truefalse ----------
{"type":"truefalse","topic":"基因组学概述","question":"基因组学以生物体基因组的全部基因为研究对象,从整体水平研究基因组的组成、结构、功能、进化及其对生物体的影响。","answer":"true","explanation":"基因组学正是以全部基因为对象,从整体水平研究基因组组成、结构、功能、进化、定位、编辑及它们对生物体的影响。","difficulty":1,"tags":["基因组学","概念"],"topic":"基因组学概述"},
{"type":"truefalse","topic":"结构基因组学与功能基因组学","question":"结构基因组学以基因功能注释为目标,功能基因组学以全基因组测序为目标。","answer":"false","explanation":"两者关系相反:结构基因组学以全基因测序为目标,功能基因组学以基因功能注释为目标。","difficulty":1,"tags":["结构基因组学","功能基因组学"],"topic":"结构基因组学与功能基因组学"},
{"type":"truefalse","topic":"全基因组测序三阶段","question":"对特定物种全基因组 DNA 测序的三个阶段依次为:DNA 测序、拼接和注释。","answer":"true","explanation":"全基因组测序包括将基因组 DNA 断开成小片段测序、按顺序拼接成完整序列、对序列包含的生物学信息进行注释三个阶段。","difficulty":1,"tags":["全基因组测序","三阶段"],"topic":"全基因组测序三阶段"},
{"type":"truefalse","topic":"大肠杆菌基因组测序","question":"大肠杆菌基因组测序中,基因组大片段 DNA 是连接到由 λ 噬菌体改造而成的载体上形成噬菌体文库的。","answer":"true","explanation":"大肠杆菌基因组 DNA 经限制性内切酶随机切割成大片段后,连接到由 λ 噬菌体改造而成的 DNA 载体上,形成噬菌体文库。","difficulty":2,"tags":["大肠杆菌","噬菌体文库"],"topic":"大肠杆菌基因组测序"},
{"type":"truefalse","topic":"人类基因组测序","question":"人类基因组测序中,基因组 DNA 被切割成约 10 kb 的小片段插入普通质粒载体中制成文库。","answer":"false","explanation":"人类基因组测序中基因组 DNA 被部分降解为 100~200 kb 的大片段,插入 BAC(细菌人工染色体)载体,而非 10 kb 小片段和普通质粒。","difficulty":2,"tags":["人类基因组","BAC"],"topic":"人类基因组测序"},
{"type":"truefalse","topic":"鸟枪测序法","question":"鸟枪测序法是将基因组 DNA 随机打断成小片段后分别测序,再依据重叠区拼接出完整序列的方法。","answer":"true","explanation":"鸟枪测序法的核心即随机打断、分别测序、重叠拼接,大肠杆菌与人类基因组测序都采用了这一基本策略。","difficulty":1,"tags":["鸟枪测序"],"topic":"鸟枪测序法"},
{"type":"truefalse","topic":"DNA测序原理(Sanger)","question":"Sanger 双脱氧链终止法中,ddNTP 因缺乏 3'-羟基,掺入后使 DNA 链延伸终止。","answer":"true","explanation":"ddNTP 3' 位为氢原子,无法形成下一个 3',5'-磷酸二酯键,故链延伸终止,产生长度各异、以 ddNTP 结尾的片段。","difficulty":2,"tags":["Sanger测序","ddNTP"],"topic":"DNA测序原理(Sanger)"},
{"type":"truefalse","topic":"DNA微阵列(基因芯片)","question":"DNA 微阵列(基因芯片)利用固定在载体上的已知序列探针与荧光标记样品核酸的互补杂交,实现基因表达的高通量检测。","answer":"true","explanation":"芯片上大量已知序列探针与标记的样品 cDNA 互补杂交,通过各点信号强度反映基因表达水平,是转录谱分析的核心技术。","difficulty":2,"tags":["DNA芯片","杂交"],"topic":"DNA微阵列(基因芯片)"},
{"type":"truefalse","topic":"基因敲除","question":"基因敲除是通过 RNA 干扰降解目标 mRNA 实现的。","answer":"false","explanation":"基因敲除通过基于同源重组的基因打靶技术将基因组中正常基因彻底删除;通过 RNA 干扰降解 mRNA 的是基因敲低。","difficulty":1,"tags":["基因敲除","RNAi"],"topic":"基因敲除"},
{"type":"truefalse","topic":"基因敲低(RNA干扰)","question":"RNA 干扰中,siRNA 引导特异性降解目标 mRNA,使对应基因表达下调。","answer":"true","explanation":"siRNA 进入细胞后借助 RISC 特异识别并降解目标 mRNA,使基因表达下调,故 RNA 干扰导致的基因功能抑制称为基因敲低。","difficulty":2,"tags":["RNAi","siRNA"],"topic":"基因敲低(RNA干扰)"},
{"type":"truefalse","topic":"基因敲除与敲低比较","question":"基因敲低能像基因敲除一样彻底消除细胞内目标蛋白质的产生。","answer":"false","explanation":"基因敲低仅降解 mRNA,基因仍存在于基因组中,蛋白质产生被显著降低但不彻底;基因敲除则在 DNA 水平彻底删除基因。","difficulty":1,"tags":["基因敲除","基因敲低"],"topic":"基因敲除与敲低比较"},
{"type":"truefalse","topic":"二维电泳(2-DE)","question":"二维电泳的第一维采用 SDS-PAGE,第二维采用等电聚焦电泳。","answer":"false","explanation":"顺序相反:二维电泳第一维为非变性等电聚焦(按等电点分离),第二维为 SDS-PAGE(按分子量分离)。","difficulty":1,"tags":["2-DE","等电聚焦","SDS-PAGE"],"topic":"二维电泳(2-DE)"},
{"type":"truefalse","topic":"二维电泳(2-DE)","question":"二维电泳第二维 SDS-PAGE 依据蛋白质等电点的差异进行分离。","answer":"false","explanation":"SDS-PAGE 依据多肽链长度(分子量)差异分离蛋白质;按等电点分离是第一维等电聚焦的功能。","difficulty":1,"tags":["2-DE","SDS-PAGE"],"topic":"二维电泳(2-DE)"},
{"type":"truefalse","topic":"蛋白质相互作用网络","question":"蛋白质-蛋白质相互作用网络分析中,常借助标签融合蛋白和特异性亲和层析分离蛋白质复合体。","answer":"true","explanation":"将亲和肽段标签与每种蛋白质融合,再以标签特异的亲和层析逐一分离与融合蛋白质相互作用的复合体,是分析相互作用网络的通用技术。","difficulty":2,"tags":["蛋白质相互作用","亲和层析"],"topic":"蛋白质相互作用网络"},
]
